# Generated by Django 3.1.4 on 2021-09-23 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_auto_20210913_1256'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_bg',
            field=models.ImageField(default='default_user_bg.jpg', upload_to='user_bgs'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_bio',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='user_image',
            field=models.ImageField(default='default_user_image.jpg', upload_to='user_images'),
        ),
    ]
