(function(g){var window=this;/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
'use strict';var s3=function(a){a.Z("cardstatechange",a.oh()&&a.Zj()?1:0)},t3=function(a,b){var c=g.Ja(b),d=c?b:arguments;
for(c=c?0:1;c<d.length;c++){if(null==a)return;a=a[d[c]]}return a},ANa=function(a){var b=g.Sl(a);
a=g.Yl(a);return new g.Cl(b.x,b.y,a.width,a.height)},BNa=function(a){return Math.pow(a,3)},CNa=function(a){return 3*a*a-2*a*a*a},w3=function(a){a=g.Ma(a);
delete u3[a];g.Vb(u3)&&v3&&v3.stop()},ENa=function(){v3||(v3=new g.M(function(){DNa()},20));
var a=v3;a.isActive()||a.start()},DNa=function(){var a=g.Oa();
g.Eb(u3,function(b){FNa(b,a)});
g.Vb(u3)||ENa()},x3=function(a,b,c,d){g.Xq.call(this);
if(!Array.isArray(a)||!Array.isArray(b))throw Error("Start and end parameters must be arrays");if(a.length!=b.length)throw Error("Start and end points must be the same length");this.u=a;this.S=b;this.duration=c;this.J=d;this.coords=[];this.progress=this.K=0;this.D=null},FNa=function(a,b){b<a.startTime&&(a.endTime=b+a.endTime-a.startTime,a.startTime=b);
a.progress=(b-a.startTime)/(a.endTime-a.startTime);1<a.progress&&(a.progress=1);a.K=1E3/(b-a.D);a.D=b;GNa(a,a.progress);1==a.progress?(a.i=0,w3(a),a.onFinish(),a.Wv()):a.wc()&&a.rB()},GNa=function(a,b){"function"===typeof a.J&&(b=a.J(b));
a.coords=Array(a.u.length);for(var c=0;c<a.u.length;c++)a.coords[c]=(a.S[c]-a.u[c])*b+a.u[c]},HNa=function(a,b){g.vf.call(this,a);
this.coords=b.coords;this.x=b.coords[0];this.y=b.coords[1];this.z=b.coords[2];this.duration=b.duration;this.progress=b.progress;this.fps=b.K;this.state=b.i},y3=function(a,b,c,d,e){x3.call(this,b,c,d,e);
this.element=a},z3=function(a,b,c,d,e){if(2!=b.length||2!=c.length)throw Error("Start and end points must be 2D");
y3.call(this,a,b,c,d,e)},A3=function(a){g.I.call(this);
this.u=a||window;this.i=[]},B3=function(a){return a.baseUrl||null},C3=function(a,b){return g.Co(g.lm(a,b,void 0),function(c){return!!c})},INa=function(a,b,c){function d(Z){var sa,kb,Pb,pb=Z.hovercardButton;
if(!pb)return null;pb=pb.subscribeButtonRenderer;if(!pb)return null;var ac=f(pb.unsubscribedButtonText),Qb=f(pb.subscribedButtonText);if(pb.subscribed){var Re=f(pb.subscriberCountWithUnsubscribeText);var Se=f(pb.subscriberCountText)}else Re=f(pb.subscriberCountText),Se=f(pb.subscriberCountWithSubscribeText);var bc=null;return Z.signinEndpoint&&(bc=t3(Z,"signinEndpoint","webNavigationEndpointData","url"),bc||(bc=null===(Pb=null===(kb=null===(sa=pb.signInEndpoint)||void 0===sa?void 0:sa.commandMetadata)||
void 0===kb?void 0:kb.webCommandMetadata)||void 0===Pb?void 0:Pb.url),!bc)?null:ac&&(Qb||bc)?{subscribed:pb.subscribed,subscribeText:ac,subscribeCount:Re,unsubscribeText:Qb,unsubscribeCount:Se,enabled:pb.enabled,signinUrl:bc,classic:Z.useClassicSubscribeButton}:null}
function e(Z){if(Z){var sa=[],kb=Z.videoId;kb&&sa.push("v="+kb);(kb=Z.playlistId)&&sa.push("list="+kb);(Z=Z.startTimeSeconds)&&sa.push("t="+Z);return"/watch?"+sa.join("&")}}
function f(Z){if(!Z)return null;var sa=Z.simpleText;return sa?sa:Z.runs?g.lm(Z.runs,function(kb){return kb.text}).join(""):null}
b=b.endscreenElementRenderer;if(!b)return null;var h=b.style,l=b.endpoint||{},m=null,n=null,p=null,q=null,t=null,u=null,x=!1,y=null,A=null,E=null,G=null,F=null;if("VIDEO"===h)l.urlEndpoint?m=l.urlEndpoint.url:m=e(l.watchEndpoint),n=!1,p=a,q=f(b.videoDuration);else if("PLAYLIST"===h)l.urlEndpoint?m=l.urlEndpoint.url:m=e(l.watchEndpoint),n=!1,p=a,t=f(b.playlistLength);else if("CHANNEL"===h){if(x=t3(l,"browseEndpoint","browseId"))u=x,m="/channel/"+u;n=!1;p="new";(x=!!b.isSubscribe)?y=d(b):A=f(b.subscribersText)}else"WEBSITE"===
h?((E=t3(l,"urlEndpoint","url"))&&(m=E),n=!0,p="new",E=b.icon.thumbnails[0].url):"CREATOR_MERCHANDISE"===h&&(b.productPrice&&(G=f(b.productPrice)),b.additionalFeesText&&(F=f(b.additionalFeesText)),(n=t3(l,"urlEndpoint","url"))&&(m=n),n=!0,p="new");a=t3(b,"title","accessibility","accessibilityData","label");var K=b.endpoint?b.endpoint.clickTrackingParams:null,W="";if(b.metadata){var L=f(b.metadata);L&&(W=L)}return{id:"element-"+c,type:h,title:f(b.title),metadata:W,callToAction:f(b.callToAction),RI:b.image,
iconUrl:E,left:Number(b.left),width:Number(b.width),top:Number(b.top),aspectRatio:Number(b.aspectRatio),startMs:Math.floor(Number(b.startMs)),endMs:Math.floor(Number(b.endMs)),videoDuration:q,playlistLength:t,channelId:u,subscribeButton:y,subscribersText:A,isSubscribe:x,targetUrl:m||null,GR:n,sessionData:K?{itct:K}:null,pW:p,Yt:a?a:null,JR:b.isPlaceholder,impressionUrls:C3(b.impressionUrls||[],B3),zR:C3(b.hovercardShowUrls||[],B3),clickUrls:C3(l.loggingUrls||[],B3),visualElement:g.yy(b.trackingParams),
productPrice:G,additionalFeesText:F}},D3=function(a,b){var c={startMs:Math.floor(Number(a.startMs)),
impressionUrls:C3(a.impressionUrls||[],B3),elements:C3(a.elements||[],function(d,e){return INa(b,d,e)})};
a.trackingParams&&(c.visualElement=g.yy(a.trackingParams));return c},E3=function(a){g.cN.call(this,a);
this.B=this.endscreen=null;this.i={};this.D={};this.C=this.u=null;this.K=[];this.V=!0;this.J=0;a=a.W();this.S=g.iF(a)||g.mF(a);this.events=new g.BD(this);g.J(this,this.events);this.events.T(this.player,g.uA("creatorendscreen"),this.onCueRangeEnter);this.events.T(this.player,g.vA("creatorendscreen"),this.onCueRangeExit);this.events.T(this.player,"resize",this.wb);this.events.T(window,"focus",this.uV);this.load();var b=g.Ag("STYLE");(g.mg("HEAD")[0]||document.body).appendChild(b);g.uf(this,function(){g.Eg(b)});
b.sheet&&(b.sheet.insertRule(".ytp-ce-playlist-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASBAMAAACk4JNkAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAIVBMVEVMaXGzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7P///91E4wTAAAACXRSTlMArBbpVOtYrReN+x2FAAAAAWJLR0QKaND0VgAAACFJREFUCNdjYCAWzIQAFBaZ6hgVYLKcJnBWGEyWvYGASwCXtBf7m4i3CQAAAABJRU5ErkJggg==) no-repeat center;background-size:18px;width:18px;height:18px}",0),b.sheet.insertRule(".ytp-ce-size-853 .ytp-ce-playlist-icon, .ytp-ce-size-1280 .ytp-ce-playlist-icon, .ytp-ce-size-1920 .ytp-ce-playlist-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYBAMAAAASWSDLAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJ1BMVEVMaXGzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7P///9RfzIKAAAAC3RSTlMAvDeyLvxYtDK9Ogx4T1QAAAABYktHRAyBs1FjAAAAK0lEQVQY02NgoBjshgO8HJoYwKiAMGAD92YHJM7uMCTO9gaEHs4FlPuZAQC8Fj8x/xHjxwAAAABJRU5ErkJggg==) no-repeat center;background-size:24px;width:24px;height:24px}",
0))},JNa=function(a){return a.player.getVideoData().D?"current":a.S?"new":"current"},F3=function(a){return"creator-endscreen-editor"===a.player.W().playerStyle},KNa=function(a){var b=a.player.getVideoData(),c=b.videoId;
a.B&&a.B.abort();c={method:"POST",onFinish:function(e){var f=a.B=null;200===e.status&&(e=e.responseText,")]}"===e.substring(0,3)&&(e=e.substring(3),f=JSON.parse(e),f=D3(f,JNa(a))));G3(a,f)},
urlParams:{v:c},withCredentials:!0};a.S&&(c.urlParams.ptype="embedded");var d=b.Hp;d&&(c.postParams={ad_tracking:d});if(b=g.Woa(b))if(b=g.Pc(b),b=g.Lc(b))a.B=g.vt(b,c)},G3=function(a,b,c){c=void 0===c?!0:c;
a.player.Te("creatorendscreen");a.u&&(a.u.dispose(),a.u=null,a.C.dispose(),a.C=null);for(var d=g.r(Object.values(a.i)),e=d.next();!e.done;e=d.next())e.value.dispose();a.i={};a.D={};0<a.K.length&&(a.K.forEach(function(l){l.dispose()}),a.K.length=0);
a.J=0;if((a.endscreen=b)&&b.elements){c&&LNa(a);c=[];d=new g.sA(b.startMs,0x7ffffffffffff,{id:"ytp-ce-in-endscreen",namespace:"creatorendscreen"});c.push(d);a.player.W().i||(a.u=new g.U({G:"div",L:"ytp-ce-shadow"}),g.RM(a.player,a.u.element,4),a.C=new g.EL(a.u,200));for(d=0;d<b.elements.length;++d){e=b.elements[d];var f=MNa(a,e);if(f){a.i[e.id]=f;a.D[e.id]=e;g.RM(a.player,f.element,4);var h=new g.sA(e.startMs,e.endMs,{id:"ytp-ce-element-"+e.id,namespace:"creatorendscreen"});c.push(h);NNa(a,f,e)}else g.yz(new g.gw("buildEndscreenElement null",
e))}a.player.Id(c);a.wb()}},LNa=function(a){var b=g.Cy(),c=g.Ey();
c&&b&&a.endscreen.visualElement&&g.Fz(void 0,c,b,[a.endscreen.visualElement])},MNa=function(a,b){var c=null;
switch(b.type){case "VIDEO":c=a.player.N("player_endscreen_ellipsis_fix")?["ytp-webkit-ellipsis"]:["yt-ui-ellipsis","yt-ui-ellipsis-2"];a={G:"div",Ha:["ytp-ce-element","ytp-ce-video"],X:{tabindex:"0","aria-label":b.Yt||"","aria-hidden":"true"},U:[{G:"div",L:"ytp-ce-element-shadow"},{G:"div",L:"ytp-ce-covering-image",X:H3(b)},{G:"div",L:"ytp-ce-covering-shadow-top"},{G:"a",L:"ytp-ce-covering-overlay",X:{href:I3(a,b.targetUrl),tabindex:"-1"},U:[{G:"div",Ha:["ytp-ce-video-title"].concat(g.v(c)),X:{dir:g.fr(b.title||
"")},va:b.title},{G:"div",L:"ytp-ce-video-duration",va:b.videoDuration||void 0}]}]};c=new g.U(a);break;case "PLAYLIST":c=a.player.N("player_endscreen_ellipsis_fix")?["ytp-webkit-ellipsis"]:["yt-ui-ellipsis","yt-ui-ellipsis-2"];a={G:"div",Ha:["ytp-ce-element","ytp-ce-playlist"],X:{tabindex:"0","aria-label":b.Yt||"","aria-hidden":"true"},U:[{G:"div",L:"ytp-ce-element-shadow"},{G:"div",L:"ytp-ce-covering-image",X:H3(b)},{G:"div",L:"ytp-ce-covering-shadow-top"},{G:"a",L:"ytp-ce-covering-overlay",X:{href:I3(a,
b.targetUrl),tabindex:"-1"},U:[{G:"div",Ha:["ytp-ce-playlist-title"].concat(g.v(c)),X:{dir:g.fr(b.title||"")},va:b.title},{G:"div",L:"ytp-ce-playlist-count",U:[{G:"div",L:"ytp-ce-playlist-icon"},{G:"div",L:"ytp-ce-playlist-count-text",va:b.playlistLength||void 0}]}]}]};c=new g.U(a);break;case "CHANNEL":c={G:"div",Ha:["ytp-ce-element","ytp-ce-channel",b.isSubscribe?"ytp-ce-channel-this":"ytp-ce-channel-that"],X:{tabindex:"0","aria-label":b.Yt||"","aria-hidden":"true"},U:[{G:"div",L:"ytp-ce-element-shadow"},
{G:"div",L:"ytp-ce-expanding-overlay",U:[{G:"div",L:"ytp-ce-expanding-overlay-hider"},{G:"div",L:"ytp-ce-expanding-overlay-background"},{G:"div",L:"ytp-ce-expanding-overlay-content",U:[{G:"div",L:"ytp-ce-expanding-overlay-body",U:[{G:"div",L:"ytp-ce-expanding-overlay-body-padding",U:[{G:"a",Ha:["ytp-ce-channel-title","ytp-ce-link"],X:{href:I3(a,b.targetUrl),target:"_blank",tabindex:"-1",dir:g.fr(b.title||"")},va:b.title},b.subscribeButton?{G:"div",L:"ytp-ce-subscribe-container",U:[{G:"div",L:"ytp-ce-channel-subscribe"}]}:
"",b.subscribersText?{G:"div",L:"ytp-ce-channel-subscribers-text",va:b.subscribersText}:"",b.metadata?{G:"div",Ha:["ytp-ce-channel-metadata","yt-ui-ellipsis","yt-ui-ellipsis-3"],va:b.metadata}:""]}]}]}]},{G:"div",L:"ytp-ce-expanding-image",X:H3(b)}]};c=new g.U(c);var d=g.ng(document,"div","ytp-ce-channel-subscribe",c.element)[0];if(b.subscribeButton&&b.channelId){g.N(d,"ytp-ce-subscribe-button");if(a.player.W().i){var e=null;var f=b.sessionData.itct}else e="endscreen",f=null;e=new g.fO(b.subscribeButton.subscribeText,
b.subscribeButton.subscribeCount,b.subscribeButton.unsubscribeText,b.subscribeButton.unsubscribeCount,!!b.subscribeButton.enabled,!!b.subscribeButton.classic,b.channelId,!!b.subscribeButton.subscribed,e,f,b.subscribeButton.signinUrl,a.player);d.appendChild(e.element);a.K.push(e)}break;case "WEBSITE":a={G:"div",Ha:["ytp-ce-element","ytp-ce-website"],X:{tabindex:"0","aria-label":b.Yt||"","aria-hidden":"true"},U:[{G:"div",L:"ytp-ce-element-shadow"},{G:"div",L:"ytp-ce-expanding-overlay",U:[{G:"div",L:"ytp-ce-expanding-overlay-hider"},
{G:"div",L:"ytp-ce-expanding-overlay-background"},{G:"div",L:"ytp-ce-expanding-overlay-content",U:[{G:"div",L:"ytp-ce-expanding-overlay-body",U:[{G:"div",L:"ytp-ce-expanding-overlay-body-padding",U:[{G:"div",L:"ytp-ce-website-title",X:{dir:g.fr(b.title||"")},va:b.title},{G:"div",L:"ytp-ce-website-metadata",va:b.metadata},{G:"a",Ha:["ytp-ce-website-goto","ytp-ce-link"],X:{href:I3(a,b.targetUrl),target:"_blank",tabindex:"-1"},va:b.callToAction}]}]}]}]},{G:"div",L:"ytp-ce-expanding-image",X:H3(b)},{G:"div",
L:"ytp-ce-expanding-icon",X:ONa(b.iconUrl)}]};c=new g.U(a);break;case "CREATOR_MERCHANDISE":c="",b.productPrice&&(c={G:"div",L:"ytp-ce-merchandise-price-container",U:[{G:"div",L:"ytp-ce-merchandise-price",va:b.productPrice}]},b.additionalFeesText&&c.U.push({G:"div",L:"ytp-ce-merchandise-additional-fees",va:b.additionalFeesText})),a={G:"div",Ha:["ytp-ce-element","ytp-ce-merchandise"],X:{tabindex:"0","aria-label":b.Yt||"","aria-hidden":"true"},U:[{G:"div",L:"ytp-ce-element-shadow"},{G:"div",L:"ytp-ce-expanding-overlay",
U:[{G:"div",L:"ytp-ce-expanding-overlay-hider"},{G:"div",L:"ytp-ce-expanding-overlay-background"},{G:"div",L:"ytp-ce-expanding-overlay-content",U:[{G:"div",L:"ytp-ce-expanding-overlay-body",U:[{G:"div",L:"ytp-ce-expanding-overlay-body-padding",U:[{G:"div",L:"ytp-ce-merchandise-title",X:{dir:g.fr(b.title||"")},va:b.title},c,{G:"div",L:"ytp-ce-merchandise-metadata",va:b.metadata},{G:"a",Ha:["ytp-ce-merchandise-goto","ytp-ce-link"],X:{href:I3(a,b.targetUrl),target:"_blank",tabindex:"-1"},va:b.callToAction}]}]}]}]},
{G:"div",L:"ytp-ce-expanding-image",X:H3(b)},{G:"div",L:"ytp-ce-merchandise-invideo-cta-container",U:[{G:"div",L:"ytp-ce-merchandise-invideo-cta",va:b.callToAction||void 0}]}]},c=new g.U(a)}b.JR&&g.N(c.element,"ytp-ce-placeholder");return c},H3=function(a){if(a.RI)var b=a.RI.thumbnails;
return ONa(b?b[b.length-1].url:null)},ONa=function(a){return a?{style:"background-image: url("+a+")"}:{}},NNa=function(a,b,c){function d(m){m&&(b.Ra("blur",function(){"none"!=m.style.display&&a.V&&m.focus()}),b.T(m,"focus",f),b.T(m,"blur",h))}
function e(m){a.J+=m;0<a.J?(g.N(b.element,"ytp-ce-force-expand"),J3(a,c.id,!0)):(g.Lq(b.element,"ytp-ce-force-expand"),g.Lq(b.element,"ytp-ce-element-hover"),J3(a,c.id,!1))}
function f(){e(1)}
function h(){e(-1)}
b.Ra("mouseenter",function(){K3(a,b,c)});
b.Ra("mouseleave",function(){L3(a,b,c)});
a.player.W().i||b.Ra("click",function(){g.N(b.element,"ytp-ce-element-hover")});
b.Ra("click",function(m){PNa(a,c,m)});
b.Ra("keypress",function(m){PNa(a,c,m)});
b.Ra("focus",function(){K3(a,b,c)});
b.Ra("blur",function(){L3(a,b,c)});
b.Ra("touchstart",function(){K3(a,b,c)});
var l=g.pg("ytp-ce-expanding-overlay-hider",b.element);l&&b.T(l,"touchstart",function(m){m=m||window.event;m.cancelBubble=!0;m.stopPropagation&&m.stopPropagation();g.Lq(b.element,"ytp-ce-element-hover");g.Lq(b.element,"ytp-ce-force-expand")});
b.Ra("keydown",function(m){a.V=9===m.keyCode&&!m.shiftKey});
d(g.pg("ytp-sb-subscribe",b.element));d(g.pg("ytp-sb-unsubscribe",b.element));b.Ra("focus",f);b.Ra("blur",h)},PNa=function(a,b,c){if(b.targetUrl&&(!c||"keypress"!==c.type||13===c.keyCode)){for(var d=c.target;d&&!g.Jq(d,"ytp-ce-element");){g.Jq(d,"subscribe-label")&&M3(a,b);
if(g.Jq(d,"ytp-ce-channel-subscribe"))return;d=g.Fg(d)}if(!d||g.Jq(d,"ytp-ce-element-hover")){c.preventDefault();c.stopPropagation();if(d=a.i[b.id])L3(a,d,b),d.element.blur();if(c.ctrlKey||c.metaKey||"new"===b.pW)M3(a,b),a.player.sendVideoStatsEngageEvent(17,void 0),a.player.pauseVideo(),c=g.Pc(I3(a,b.targetUrl)),c=g.Lc(c),g.GJ(c,void 0,b.sessionData);else{var e=a.player.getVideoData().D,f=function(){var h=I3(a,b.targetUrl),l=b.sessionData,m=g.Fs(h);e&&m&&(m.v||m.list)?a.player.Fj(m.v,l,m.list,!1):
g.FJ(h,l)};
M3(a,b,function(){a.player.sendVideoStatsEngageEvent(17,f)})}}}},I3=function(a,b){a=a.player.W();
if(b){if(b.startsWith("//"))return a.protocol+":"+b;if(b.startsWith("/"))return g.LF(a)+b}else return"";return b},K3=function(a,b,c){g.Jq(b.element,"ytp-ce-element-hover")||("VIDEO"===c.type||"PLAYLIST"===c.type?g.N(b.element,"ytp-ce-element-hover"):a.player.W().i?(new g.M(function(){g.N(b.element,"ytp-ce-element-hover")},200)).start():g.N(b.element,"ytp-ce-element-hover"),N3(a,c.zR),J3(a,c.id,!0))},L3=function(a,b,c){g.Lq(b.element,"ytp-ce-element-hover");
g.Lq(b.element,"ytp-ce-force-expand");J3(a,c.id,!1)},J3=function(a,b,c){a.u&&(c?a.C.show():a.C.hide());
for(var d=g.r(Object.keys(a.i)),e=d.next();!e.done;e=d.next())e=e.value,e!==b&&g.O(a.i[e].element,"ytp-ce-element-shadow-show",c)},N3=function(a,b,c){function d(){f||(e++,e===b.length&&(h.stop(),c&&c()))}
if(!b||0===b.length||F3(a))c&&c();else{b=QNa(a,b);var e=0,f=!1,h=new g.M(function(){f=!0;c&&c()},1E3,a);
h.start();for(a=0;a<b.length;a++)g.Vu(b[a],d)}},M3=function(a,b,c){N3(a,b.clickUrls,c);
(a=g.Ey())&&b.GR&&g.Oz(a,b.visualElement)},QNa=function(a,b){var c=a.player.getVideoData().clientPlaybackNonce;
a=a.player.getCurrentTime().toFixed(2);c={CPN:c,AD_CPN:c,MT:a};a=[];for(var d=0;d<b.length;d++)a.push(RNa(b[d],c));return a},RNa=function(a,b){return a.replace(/%5B[a-zA-Z_:]+%5D|\[[a-zA-Z_:]+\]/g,function(c){var d=unescape(c);
d=d.substring(1,d.length-1);return b[d]?escape(b[d]):c})},SNa=function(a){return"string"===typeof a?a:""},O3=function(a,b,c){for(var d in b)if(b[d]===a)return a;
return c},TNa=function(a,b,c,d){this.value=a;
this.target=b;this.showLinkIcon=c;this.i=d},P3=function(a){return a.value?a.value:null},Q3=function(a){if(!a)return null;
var b=g.Pc(SNa(a.value));b=g.Lc(b);if(!b)return null;var c=O3(a.target,UNa,"current");if(null==c)a=null;else{var d=a.show_link_icon;a=new TNa(b,c,"true"===d||"false"===d?"true"===d:!0,null!=a.pause_on_navigation?a.pause_on_navigation:!0)}return a},VNa=function(a,b,c){this.type=a;
this.trigger=b;this.url=c},YNa=function(a){if(!a)return null;
var b=O3(a.type,WNa),c=O3(a.trigger,XNa);a=a.url;a=Array.isArray(a)&&a.length?a[0]:a;a=Q3(a?a:null);return b?new VNa(b,c,a):null},R3=function(a,b,c,d,e){this.id=a;
this.type=b;this.style=c;this.data=e;this.action=d||[]},ZNa=function(a,b){return g.db(a.action,b,void 0)},$Na=function(a,b){this.context=a;
this.i=b},T3=function(a){return a.customMessage?S3("div","iv-card-message",a.customMessage):""},U3=function(a,b){a="background-image: url("+a+");";
var c=[];b&&c.push(b);return{G:"div",L:"iv-card-image",X:{style:a},U:c}},V3=function(a){if(!a.metaInfo||0===a.metaInfo.length)return"";
var b=[];a=g.r(a.metaInfo);for(var c=a.next();!c.done;c=a.next())b.push(S3("li","",c.value));return{G:"ul",L:"iv-card-meta-info",U:b}},S3=function(a,b,c){b?"string"===typeof b?b={"class":b}:Array.isArray(b)&&(b={"class":b.join(" ")}):b={};
b.dir=g.fr(c);return{G:a,X:b,va:c}},aOa=function(a){if(!a.customMessage)return"";
var b=["iv-card-action","iv-card-primary-link"],c={};a.xx&&(b.push("iv-card-action-icon"),c.style="background-image: url("+a.xx+");");c.dir=g.fr(a.customMessage);var d=[{G:"span",va:a.customMessage}];a.showLinkIcon&&(d.push("\u00a0"),d.push({G:"span",L:"iv-card-link-icon"}));return{G:"div",Ha:b,X:c,U:d}},W3=function(a,b,c,d){if(d){b=g.r(b);
for(var e=b.next();!e.done;e=b.next())a.i(e.value,d,c.id,c.sessionData,c.tracking.click,5)}},bOa=function(a,b){this.merchant=a;
this.price=b},cOa=function(a){var b;
(b=a)&&!(b=1<a.length?"/"===a.charAt(0)&&"/"!==a.charAt(1):"/"===a)&&(b=a.replace(/^(https?:)?\/\//,""),b=b.split("/",1),b=!b||1>b.length||!b[0]?[]:b[0].toLowerCase().split(".").reverse(),b="com"===b[0]&&"youtube"===b[1]||"be"===b[0]&&"youtu"===b[1]);return b?-1===a.indexOf("/redirect?"):!1},dOa=function(a,b){return b?b:cOa(a)?"current":"new"},X3=function(a,b){g.I.call(this);
var c=this;this.element=a;this.context=b;this.bb=!1;this.Pa=new Map;this.Sa=new Map;this.context.I.addEventListener(g.uA("annotations_module"),function(d){(d=c.Pa.get(d))&&d.apply(c)});
this.context.I.addEventListener(g.vA("annotations_module"),function(d){(d=c.Sa.get(d))&&d.apply(c)})},Y3=function(a,b,c,d,e,f,h){a.context.i.Ra(b,"click",function(l){a.sB(c,d,e,f||[],h||0,l)});
a.context.i.Ra(b,"touchstart",function(){a.bb=!1});
a.context.i.Ra(b,"touchmove",function(){a.bb=!0})},eOa=function(a){if(a.urlEndpoint&&a.urlEndpoint.url)return a.urlEndpoint.url;
if(a.watchEndpoint&&a.watchEndpoint.videoId){var b="/watch?v="+a.watchEndpoint.videoId;a.watchEndpoint.playlistId&&(b+="&list="+a.watchEndpoint.playlistId);a.watchEndpoint.index&&(b+="&index="+a.watchEndpoint.index);a.watchEndpoint.startTimeSeconds&&(b+="&t="+a.watchEndpoint.startTimeSeconds);return b}return null},Z3=function(a,b,c){return{impression:(a.impressionLoggingUrlsV2s||[]).map(function(d){return d.baseUrl||""}),
click:(c.loggingUrls||[]).map(function(d){return d.baseUrl||""}),
close:(b.dismissLoggingUrlsV2s||[]).map(function(d){return d.baseUrl||""}),
UM:(b.impressionLoggingUrlsV2s||[]).map(function(d){return d.baseUrl||""}),
qA:(b.clickLoggingUrlsV2s||[]).map(function(d){return d.baseUrl||""})}},b4=function(a,b,c){X3.call(this,b,c);
var d=this;this.I=a;this.eventId=null;this.La=this.kb=this.B=this.Td=!1;this.xa=null;this.cards=[];this.ob=this.S=this.Ga=this.D=this.Ka=this.i=null;this.ea=[];this.K=this.pe=this.Ba=null;this.J=0;this.Aa=new g.M(g.Ga,c.Y.Uc?4E3:3E3);g.J(this,this.Aa);this.Za=new g.M(g.Ga);g.J(this,this.Za);this.ma=new $Na(c,function(e,f,h,l,m,n){Y3(d,e,f,h,l,m,n)});
this.V=new g.U({G:"div",L:"iv-drawer",X:{id:"iv-drawer"},U:[{G:"div",L:"iv-drawer-header",X:{"aria-role":"heading"},U:[{G:"span",L:"iv-drawer-header-text"},{G:"button",Ha:["iv-drawer-close-button","ytp-button"],X:{"aria-label":"Hide cards",tabindex:"0"}}]},{G:"div",L:"iv-drawer-content"}]});g.J(this,this.V);this.C=this.V.element;this.Wa=new g.EL(this.V,330);g.J(this,this.Wa);this.gb=g.pg("iv-drawer-header-text",this.C);this.u=g.pg("iv-drawer-content",this.C);this.addCueRange(0,1E3*c.videoData.lengthSeconds,
"",function(){d.kb&&$3(d,"YOUTUBE_DRAWER_AUTO_OPEN")},function(){(d.kb=d.B)&&a4(d)})},fOa=function(a,b){b=b.data;
b.autoOpenMs&&a.addCueRange(b.autoOpenMs,0x8000000000000,"",function(){$3(a,"YOUTUBE_DRAWER_AUTO_OPEN")});
b.autoCloseMs&&a.addCueRange(b.autoCloseMs,0x8000000000000,"",function(){a4(a)});
var c=b.headerText;g.Hg(a.gb,c);a.S&&a.S.setAttribute("title",c);b.eventId&&(a.eventId=b.eventId);a.Ba=g.yy(b.trackingParams);a.K=g.yy(b.closeTrackingParams);a.pe=g.yy(b.iconTrackingParams)},gOa=function(a,b){var c=b.cardId?b.cardId:"cr:"+a.J;
if(b.content.simpleCardContentRenderer){if(!b.cueRanges.length)return;var d=b.content.simpleCardContentRenderer,e=b.teaser.simpleCardTeaserRenderer,f=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.J,type:"simple",teaserText:g.zA(e.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,sessionData:c4(a,c,b,d),sponsored:!1,tracking:Z3(d,e,d.command),ul:d.trackingParams?g.yy(d.trackingParams):null,Ii:e.trackingParams?
g.yy(e.trackingParams):null,pe:f&&f.trackingParams?g.yy(f.trackingParams):null,imageUrl:d4(d.image.thumbnails,290).url,displayDomain:d.displayDomain?g.zA(d.displayDomain):null,showLinkIcon:!!d.showLinkIcon,xx:null,title:d.title?g.zA(d.title):"",customMessage:d.callToAction?g.zA(d.callToAction):"",url:d.command.urlEndpoint.url?Q3({pause_on_navigation:!a.context.videoData.isLivePlayback,target:"new",value:d.command.urlEndpoint.url}):null};e4(a,b)}else if(b.content.collaboratorInfoCardContentRenderer){if(!b.cueRanges.length)return;
d=b.content.collaboratorInfoCardContentRenderer;e=b.teaser.simpleCardTeaserRenderer;f=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.J,type:"collaborator",teaserText:g.zA(e.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,sessionData:c4(a,c,b,d),sponsored:!1,tracking:Z3(d,e,d.endpoint),ul:d.trackingParams?g.yy(d.trackingParams):null,Ii:e.trackingParams?g.yy(e.trackingParams):null,pe:f&&f.trackingParams?
g.yy(f.trackingParams):null,channelId:d.endpoint.browseEndpoint.browseId,customMessage:d.customText?g.zA(d.customText):null,profileImageUrl:d4(d.channelAvatar.thumbnails,290).url,title:d.channelName?g.zA(d.channelName):"",metaInfo:[d.subscriberCountText?g.zA(d.subscriberCountText):""],url:Q3({pause_on_navigation:!a.context.videoData.isLivePlayback,target:"new",value:d.endpoint.browseEndpoint.canonicalBaseUrl?d.endpoint.browseEndpoint.canonicalBaseUrl:"/channel/"+d.endpoint.browseEndpoint.browseId})};
e4(a,b)}else if(b.content.playlistInfoCardContentRenderer){if(!b.cueRanges.length)return;d=b.content.playlistInfoCardContentRenderer;e=b.teaser.simpleCardTeaserRenderer;f=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.J,type:"playlist",teaserText:g.zA(e.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,sessionData:c4(a,c,b,d),sponsored:!1,tracking:Z3(d,e,d.action),ul:d.trackingParams?g.yy(d.trackingParams):
null,Ii:e.trackingParams?g.yy(e.trackingParams):null,pe:f&&f.trackingParams?g.yy(f.trackingParams):null,Ow:d4(d.playlistThumbnail.thumbnails,258).url,customMessage:d.customMessage?g.zA(d.customMessage):null,playlistVideoCount:g.zA(d.playlistVideoCount),title:d.playlistTitle?g.zA(d.playlistTitle):"",metaInfo:[d.channelName?g.zA(d.channelName):"",d.videoCountText?g.zA(d.videoCountText):""],url:Q3({pause_on_navigation:!a.context.videoData.isLivePlayback,target:"new",value:eOa(d.action)})};e4(a,b)}else if(b.content.videoInfoCardContentRenderer){if(!b.cueRanges.length)return;
d=b.content.videoInfoCardContentRenderer;e=b.teaser.simpleCardTeaserRenderer;f=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.J,type:"video",teaserText:g.zA(e.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,sessionData:c4(a,c,b,d),sponsored:!1,tracking:Z3(d,e,d.action),ul:d.trackingParams?g.yy(d.trackingParams):null,Ii:e.trackingParams?g.yy(e.trackingParams):null,pe:f&&f.trackingParams?g.yy(f.trackingParams):
null,Ow:d4(d.videoThumbnail.thumbnails,258).url,videoDuration:d.lengthString?g.zA(d.lengthString):null,customMessage:d.customMessage?g.zA(d.customMessage):null,title:d.videoTitle?g.zA(d.videoTitle):"",metaInfo:[d.channelName?g.zA(d.channelName):"",d.viewCountText?g.zA(d.viewCountText):""],isLiveNow:!!d.badge,url:Q3({pause_on_navigation:!a.context.videoData.isLivePlayback,target:"new",value:eOa(d.action)})};e4(a,b)}a.J++},d4=function(a,b){for(var c=-1,d=-1,e=0;e<a.length;e++){if(a[e].height===b||290===
a[e].width)return a[e];
((a[e].height||0)<b||290>(a[e].width||0))&&(0>c||(a[c].height||0)<(a[e].height||0)||(a[c].width||0)<(a[e].width||0))?c=e:((a[e].height||0)>=b||290<=(a[e].width||0))&&(0>d||(a[d].height||0)>(a[e].height||0)||(a[d].width||0)>(a[e].width||0))&&(d=e)}return a[0<=d?d:c]},c4=function(a,b,c,d){return{feature:c.feature?c.feature:"cards",
src_vid:a.context.videoData.videoId,annotation_id:b,ei:a.context.videoData.eventId||"",itct:d.trackingParams||""}},iOa=function(a,b){if(b=hOa(a,b))b===a.i&&(a.i=null),a.I.removeCueRange(b.card.id),g.Eg(b.hC),g.nb(a.cards,b),a.zx(),f4(a)},$3=function(a,b,c){if(!a.B){a.Wa.show();
a.Ka=new g.M(function(){g.N(a.context.I.getRootNode(),g.WT.IV_DRAWER_OPEN)},0);
a.Ka.start();a.xa=g.uu(a.u,"mousewheel",function(h){a.Aa.start();h.preventDefault();h=h||window.event;var l=0;"MozMousePixelScroll"==h.type?l=0==(h.axis==h.HORIZONTAL_AXIS)?h.detail:0:window.opera?l=h.detail:l=0==h.wheelDelta%120?"WebkitTransform"in document.documentElement.style?window.chrome&&0==navigator.platform.indexOf("Mac")?h.wheelDeltaY/-30:h.wheelDeltaY/-1.2:h.wheelDelta/-1.6:h.wheelDeltaY/-3;if(h=l)a.u.scrollTop+=h});
a.B=!0;var d=g.Ey();d&&a.Ba&&a.K&&g.Mz(d,[a.Ba,a.K]);b={TRIGGER_TYPE:b};for(var e=g.r(a.cards),f=e.next();!f.done;f=e.next())f=f.value,f.BK||(f.BK=!0,jOa(a.context.logger,f.card.tracking.impression,b)),d&&g.Mz(d,[f.card.ul]);s3(a.I);c&&(a.D=new g.M(function(){a.Ga=a.S;a.ob.focus()},330),a.D.start())}},a4=function(a){a.B&&(a.Wa.hide(),g.vu(a.xa),a.xa=null,g.Lq(a.context.I.getRootNode(),g.WT.IV_DRAWER_OPEN),a.B=!1,s3(a.I),a.D&&a.D.stop(),a.D=new g.M(function(){a.Ga&&(a.Ga.focus(),a.Ga=null)},330),a.D.start())},
lOa=function(a){g.Kq(a.element,[g.WT.STOP_EVENT_PROPAGATION,
"iv-drawer-manager"]);g.RM(a.I,a.C,5);kOa(a);a.S=g.pg("ytp-cards-button",a.I.getRootNode());a.ob=g.pg("iv-drawer-close-button",a.C);a.Td=!0},kOa=function(a){var b=g.pg("iv-drawer-close-button",a.C);
a.context.i.Ra(b,"click",a.nQ,a);a.context.i.Ra(a.u,"touchend",function(){a.Aa.start()});
a.context.i.Ra(a.u,"scroll",a.zQ,a);a.context.u.subscribe("onHideControls",function(){a.La=!0});
a.context.u.subscribe("onShowControls",function(){a.La=!1});
a.context.u.subscribe("onVideoAreaChange",function(){a.La=g.Jq(a.I.getRootNode(),"ytp-autohide")});
a.ea.push(g.bv("iv-button-shown",a.SR,a));a.ea.push(g.bv("iv-button-hidden",a.RR,a));a.ea.push(g.bv("iv-teaser-shown",a.TO,a));a.ea.push(g.bv("iv-teaser-hidden",a.TR,a));a.ea.push(g.bv("iv-teaser-clicked",a.SO,a))},e4=function(a,b){a.Td||lOa(a);
iOa(a,b.id);var c=mOa(a,b);if(c){var d={card:b,hC:c.element,BK:!1},e=nOa(a,d);g.ub(a.cards,e,0,d);c.Ea(a.u,e);a.zx();b.autoOpen?a.addCueRange(b.startMs,0x8000000000000,b.id,function(){a.B||(a.i=d,f4(a),oOa(a,d),$3(a,"YOUTUBE_DRAWER_AUTO_OPEN",!1))}):(c=1E3*a.context.I.getCurrentTime(),5E3>c&&c>b.startMs&&pOa(a,d),a.addCueRange(b.startMs,b.startMs+1,b.id,function(){pOa(a,d)}),f4(a))}},mOa=function(a,b){switch(b.type){case "simple":a=a.ma;
var c=b.displayDomain?{G:"div",L:"iv-card-image-text",va:b.displayDomain}:void 0;var d=aOa(b);c={G:"div",Ha:["iv-card"],U:[{G:"a",L:"iv-click-target",X:{href:b.url?P3(b.url)||"":""},U:[U3(b.imageUrl,c),{G:"div",L:"iv-card-content",U:[S3("h2",void 0,b.title),d]}]}]};c=new g.U(c);W3(a,g.og("iv-click-target",c.element),b,b.url);return c;case "collaborator":return a=a.ma,c={G:"div",Ha:["iv-card","iv-card-channel"],U:[{G:"a",Ha:["iv-click-target"],X:{href:P3(b.url)||"","data-ytid":b.channelId},U:[U3(b.profileImageUrl),
{G:"div",L:"iv-card-content",U:[T3(b),{G:"h2",L:"iv-card-primary-link",va:b.title},V3(b)]}]}]},c=new g.U(c),W3(a,g.og("iv-click-target",c.element),b,b.url),c;case "playlist":return a=a.ma,c={G:"div",Ha:["iv-card","iv-card-playlist"],U:[{G:"a",L:"iv-click-target",X:{href:P3(b.url)||""},U:[U3(b.Ow,{G:"div",L:"iv-card-image-overlay",U:[{G:"span",L:"iv-card-playlist-video-count",va:b.playlistVideoCount}]}),{G:"div",L:"iv-card-content",U:[T3(b),S3("h2","iv-card-primary-link",b.title),V3(b)]}]}]},c=new g.U(c),
W3(a,g.og("iv-click-target",c.element),b,b.url),c;case "productListing":a=a.ma;var e=!g.ib(b.offers);c=["iv-card"];d="";var f=aOa(b);e&&(c.push("iv-card-product-listing"),d="iv-card-primary-link",f=b.offers[0],e=[],f.price&&e.push({G:"div",L:"iv-card-offer-price",va:f.price}),f.merchant&&e.push({G:"div",L:"iv-card-offer-merchant",va:f.merchant}),f={G:"div",U:e});e=b.url?P3(b.url)||"":"";c={G:"div",Ha:c,X:{tabindex:"0"},U:[{G:"a",Ha:["iv-card-image","iv-click-target"],X:{style:"background-image: url("+
b.imageUrl+");",href:e,"aria-hidden":"true",tabindex:"-1"}},{G:"div",L:"iv-card-content",U:[b.sponsored?{G:"div",L:"iv-card-sponsored",U:["Sponsored",{G:"div",L:"iv-ad-info-container",U:[{G:"div",L:"iv-ad-info",va:"{{adInfo}}"},{G:"div",L:"iv-ad-info-icon-container",U:[{G:"div",L:"iv-ad-info-icon"},{G:"div",L:"iv-ad-info-callout"}]}]}]}:"",{G:"a",L:"iv-click-target",X:{href:e},U:[S3("h2",d,b.title),f]}]}]};c=new g.U(c);d=g.Ag("span");g.Hg(d,"You are seeing this product because we think it is relevant to the video. Google may be compensated by the merchant.");
c.dd(d,"adInfo");W3(a,g.og("iv-click-target",c.element),b,b.url);return c;case "video":return a=a.ma,d=b.videoDuration?{G:"span",L:"iv-card-video-duration",va:b.videoDuration}:void 0,f=b.isLiveNow?{G:"span",Ha:["yt-badge","yt-badge-live"],va:"LIVE NOW"}:null,e={G:"div",Ha:["iv-card","iv-card-video"],U:[{G:"a",L:"iv-click-target",X:{href:(null===(c=b.url)||void 0===c?void 0:P3(c))||""},U:[U3(b.Ow,d),{G:"div",L:"iv-card-content",U:[T3(b),S3("h2","iv-card-primary-link",b.title),V3(b),f]}]}]},c=new g.U(e),
W3(a,g.og("iv-click-target",c.element),b,b.url),c;default:return null}},nOa=function(a,b){if(0===a.cards.length)return 0;
a=g.eb(a.cards,function(c){return b.card.startMs>c.card.startMs||b.card.startMs===c.card.startMs&&b.card.timestamp>=c.card.timestamp?!0:!1});
return-1===a?0:a+1},qOa=function(a){return a.i?"productListing"===a.i.card.type:g.mm(a.cards,function(b){return"productListing"===b.card.type})},f4=function(a){g.O(a.I.getRootNode(),"ytp-cards-shopping-active",qOa(a))},pOa=function(a,b){if(!g.Jq(a.I.getRootNode(),"ytp-cards-teaser-shown")){if(a.i!==b){var c=g.Ey(),d=a.i?a.i.card.pe:a.pe;
c&&d&&g.Nz(c,[d]);a.i=b;f4(a)}if(c="none"!=a.element.style.display)a.context.I.W().N("html5_enable_single_video_vod_ivar_on_pacf")||2!==a.context.I.getPresentingPlayerType()?(c=a.context.I.getPlayerState(),d=0===c&&0===a.context.I.getCurrentTime(),c=1===c||3===c||d):c=1===a.context.I.getAdState();c&&b.card.teaserDurationMs&&a.I.Gs(!0,{teaserText:b.card.teaserText,durationMs:b.card.teaserDurationMs});a.Za.isActive()||((!a.B||!a.Aa.isActive()&&a.La)&&oOa(a,b),a.Za.start(910+b.card.teaserDurationMs))}},
oOa=function(a,b){a.V.yb?(b=new x3([0,
a.u.scrollTop],[0,b.hC.offsetTop],600,CNa),a.context.B.Ra(b,"animate",function(c){a.u.scrollTop=c.y}),a.context.B.Ra(b,"finish",function(c){a.u.scrollTop=c.y}),b.play()):(g.VK(a.V,!0),a.u.scrollTop=b.hC.offsetTop,g.VK(a.V,!1))},g4=function(a){return a.i&&a.i.card?a.i.card:a.cards[0]&&a.cards[0].card?a.cards[0].card:null},hOa=function(a,b){return g.db(a.cards,function(c){return c.card.id===b})},h4=function(a,b,c){X3.call(this,a,b);
this.annotation=c;this.isActive=!1},rOa=function(a){var b=a.annotation.data;
"start_ms"in b&&"end_ms"in b&&a.addCueRange(b.start_ms,b.end_ms,a.annotation.id,function(){a.show()},function(){a.hide()})},i4=function(a,b,c){h4.call(this,a,b,c);
this.u=null;this.K=!1;this.B=null;this.C=!1;this.i=this.J=this.D=null},sOa=function(a,b){var c=void 0===c?0:c;
var d=ANa(b).width;g.Ql(b,d);c=new z3(b,[d,b.offsetTop],[d-d-c,b.offsetTop],200,BNa);g.J(a,c);a.context.B.Ra(c,"begin",function(){g.Zl(b,!0)});
c.play()},vOa=function(a,b){if(b.channel_name){var c=a.createElement({G:"div",
Ha:["iv-branding-context-name"],va:b.channel_name}),d=a.createElement({G:"div",Ha:["iv-branding-context-subscribe"]}),e=b.standalone_subscribe_button_data;e&&(a.i=new g.fO(e.subscribeText,e.subscribeCount,e.unsubscribeText,e.unsubscribeCount,!!e.enabled,!!e.classic,b.channel_id,!!e.subscribed,e.feature,b.session_data.itct,e.signInUrl,a.context.I),a.i.Ea(d));var f=a.createElement({G:"div",Ha:["iv-branding-context-subscribe-caret"]}),h=a.createElement({G:"div",Ha:["branding-context-container-inner"]});
h.appendChild(f);h.appendChild(c);h.appendChild(d);g.Zl(h,!1);var l=a.createElement({G:"div",Ha:["branding-context-container-outer"]});l.appendChild(h);g.Jl(l,"right",b.image_width+"px");a.element.appendChild(l);a.B=new g.M(function(){tOa(a,h,l)},500);
g.J(a,a.B);a.context.i.Ra(a.element,"mouseover",function(){uOa(a,h,l,f,b.image_height)});
a.context.i.Ra(a.element,"mouseout",function(){a.B.start()})}},uOa=function(a,b,c,d,e){a.B.stop();
if(!a.C){var f=g.Yl(b);a.i||(b.style.width=g.Pl(f.width,!0),c.style.width=g.Pl(f.width,!0));g.Jl(d,"top",f.height-Math.max(Math.min(f.height,e)/2+10,20)+"px");g.Jl(d,"right","1px");a.C=!0;g.Zl(b,!0);a.D=new g.M(function(){g.N(this.element,"iv-branding-active")},0,a);
a.D.start()}},tOa=function(a,b,c){g.Lq(a.element,"iv-branding-active");
a.J=new g.M(function(){g.Zl(b,!1);a.i||(c.style.width=g.Pl(0,!0))},250);
a.J.start();a.C=!1},wOa=function(a,b,c,d,e,f,h){this.i=a;
this.B=b;this.Y=c;this.videoData=d;this.logger=e;this.I=f;this.u=h},j4=function(a,b,c){h4.call(this,a,b,c);
var d=this;this.S=this.isCollapsed=this.V=!1;this.J=5E3;this.u=this.B=this.i=this.C=null;this.K=this.createElement({G:"div",Ha:["iv-promo-contents"]});this.D=new g.M(function(){d.i.setAttribute("aria-hidden","true");g.Zl(d.B,!1);g.Zl(d.u,!0)},700,this);
g.J(this,this.D)},xOa=function(a){var b=a.annotation.data;
if("cta"===a.annotation.style)var c=6;else if("video"===a.annotation.style||"playlist"===a.annotation.style)c=7;a.J=b.collapsedelay_ms||a.J;var d=["iv-promo","iv-promo-inactive"];a.element.setAttribute("aria-hidden","true");a.element.setAttribute("aria-label","Promotion");a.element.tabIndex=0;var e=a.annotation.Rd(),f=b.image_url;if(f){var h=a.createElement({G:"div",Ha:["iv-promo-img","iv-click-target"]});f=a.createElement({G:"img",X:{src:f,"aria-hidden":"true"}});h.appendChild(f);b.video_duration&&
!b.is_live?(f=a.createElement({G:"span",L:"iv-promo-video-duration",va:b.video_duration}),h.appendChild(f)):b.playlist_length&&(f=a.createElement({G:"span",L:"iv-promo-playlist-length",va:b.playlist_length.toString()}),h.appendChild(f));e&&Y3(a,h,e,a.annotation.id,b.session_data,void 0,c)}e?(f=a.createElement({G:"a",L:"iv-promo-txt"}),g.od(f,P3(e)),a.i=f):a.i=a.createElement({G:"div",L:"iv-promo-txt"});switch(a.annotation.style){case "cta":case "website":var l=a.createElement({G:"p",U:[{G:"strong",
va:b.text_line_1}]});var m=a.createElement({G:"p",U:[{G:"span",L:"iv-promo-link",va:b.text_line_2}]});if(f=b.text_line_3){d.push("iv-promo-website-card-cta-redesign");var n=a.createElement({G:"button",Ha:["iv-promo-round-expand-icon","ytp-button"]});f=a.createElement({G:"button",Ha:["iv-button","iv-promo-button"],U:[{G:"span",L:"iv-button-content",va:f}]});var p=a.createElement({G:"div",L:"iv-promo-button-container"});p.appendChild(f);e&&Y3(a,a.element,e,a.annotation.id,b.session_data,void 0,c)}g.N(a.i,
"iv-click-target");e&&Y3(a,a.i,e,a.annotation.id,b.session_data,void 0,c);break;case "playlist":case "video":l=a.createElement({G:"p",U:[{G:"span",va:b.text_line_1}]}),m=a.createElement({G:"p",U:[{G:"strong",va:b.text_line_2}]}),b.is_live&&(l=m,m=a.createElement({G:"span",Ha:["yt-badge","iv-promo-badge-live"],va:"LIVE NOW"})),g.N(a.i,"iv-click-target"),e&&Y3(a,a.i,e,a.annotation.id,b.session_data,void 0,c),d.push("iv-promo-video")}l&&a.i.appendChild(l);m&&a.i.appendChild(m);a.K.appendChild(a.i);p&&
a.K.appendChild(p);c=a.createElement({G:"div",L:"iv-promo-actions"});a.u=a.createElement({G:"button",Ha:["iv-promo-expand","ytp-button"]});a.u.title="Expand";a.context.i.Ra(a.u,"click",function(q){k4(a,5E3,q)});
c.appendChild(a.u);g.Zl(a.u,!1);a.context.i.Ra(a.element,"mouseover",a.eR,a);a.context.i.Ra(a.element,"mouseout",a.dR,a);a.context.i.Ra(a.element,"touchend",function(q){k4(a,5E3,q)});
a.B=a.createElement({G:"button",Ha:["iv-promo-close","ytp-button"]});a.B.title="Close";a.context.i.Ra(a.B,"click","cta"===a.annotation.style&&b.text_line_3?a.ZQ:a.YQ,a);c.appendChild(a.B);g.Kq(a.element,d);h&&(a.element.appendChild(h),n&&h.appendChild(n));a.element.appendChild(a.K);a.element.appendChild(c)},k4=function(a,b,c){c.stopPropagation();
yOa(a);zOa(a,b);a.i.focus()},AOa=function(a){a.isCollapsed||a.S||a.C||(g.N(a.element,"iv-promo-collapsed"),a.isCollapsed=!0,a.D.start())},yOa=function(a){a.D.stop();
a.isCollapsed&&(g.Mq(a.element,["iv-promo-collapsed","iv-promo-collapsed-no-delay"]),a.isCollapsed=!1,a.i&&a.i.removeAttribute("aria-hidden"),g.Zl(a.u,!1),g.Zl(a.B,!0))},zOa=function(a,b){a.C||(a.C=g.th(function(){l4(this);
AOa(this)},b,a))},l4=function(a){a.C&&(g.C.clearTimeout(a.C),a.C=null)},BOa=function(a){this.I=a},jOa=function(a,b,c){b&&(c?m4(a,b.map(function(d){return g.wq(d,c)})):m4(a,b))},m4=function(a,b,c,d){var e=1,f=void 0,h=-1;
if(c){var l=!1;f=function(){e--;e||l||(clearTimeout(h),l=!0,c())};
h=setTimeout(function(){l=!0;c()},1E3)}b=g.r(b||[]);
for(var m=b.next();!m.done;m=b.next())m=m.value,e++,g.Vu(m,f);d&&(e++,0!==d&&a.I.sendVideoStatsEngageEvent(d,f))},n4=function(a){g.cN.call(this,a);
var b=this;this.V=!1;this.loadNumber=0;this.K={};this.logger=new BOa(this.player);this.D=new g.BD(this);this.J=this.B=null;this.events=new g.BD(this);this.S=this.i=null;this.ea=[];g.J(this,this.D);this.D.T(this.player,"onVideoAreaChange",function(){b.Z("onVideoAreaChange")});
this.D.T(this.player,"onHideControls",function(){b.Z("onHideControls")});
this.D.T(this.player,"onShowControls",function(){b.Z("onShowControls")});
this.D.T(this.player,"resize",function(d){b.Z("resize",d)});
this.D.T(this.player,"presentingplayerstatechange",function(d){b.Z("presentingplayerstatechange",d)});
this.subscribe("presentingplayerstatechange",this.UO,this);this.subscribe("resize",this.xz,this);this.player.W().V.subscribe("vast_info_card_add",this.PL,this);g.J(this,this.events);this.ma=this.createElement({G:"div",L:"video-custom-annotations"});this.u=new g.U({G:"div",Ha:["ytp-player-content","ytp-iv-player-content"]});g.J(this,this.u);g.RM(this.player,this.u.element,4);this.u.hide();this.C=new g.U({G:"div",Ha:["ytp-iv-video-content"]});g.J(this,this.C);a=this.createElement({G:"div",L:"video-annotations"});
a.appendChild(this.ma);this.C.element.appendChild(a);this.kq()&&this.load();var c=this.createElement({G:"style"});(g.mg("HEAD")[0]||document.body).appendChild(c);g.uf(this,function(){g.Eg(c)});
if(a=c.sheet)a.insertRule(".iv-promo .iv-promo-contents .iv-promo-txt .iv-promo-link:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABQAAAAUBAMAAAB/pwA+AAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAHlBMVEVMaXH////////////////////////////////////Z6AnKAAAACXRSTlMA+/A2IuI1mJIldm0CAAAAAWJLR0QB/wIt3gAAAEVJREFUCNdjYGCYCQUMBJlACOIzIDElIcyZkwxgojOVWWDMSQauMKYySySUOSnBdSaUOZ0lEsac2YqwYiZ+JhwgM7E5HACgzVCI/YJ59AAAAABJRU5ErkJggg==) no-repeat center;background-size:10px;width:10px;height:10px}",
0),a.insertRule(".iv-promo .iv-promo-actions .iv-promo-close:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAkAAAAJBAMAAAASvxsjAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXH///////////////////////////////////////////9tKdXLAAAAC3RSTlMAVaQDpaimqQbl5rjXUFUAAAABYktHRAH/Ai3eAAAAPUlEQVQI12MQMmAwEmDwDmaOTmAw39663YCBuXp2MQMDQ+fOBgYG5ujVwQwMptvbgeLaxczVCQwiBgxmAgBkXg1FN5iwiAAAAABJRU5ErkJggg==) no-repeat center;background-size:9px;width:9px;height:9px}",
0),a.insertRule(".iv-promo .iv-promo-actions .iv-promo-expand:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAQAAAAJBAMAAADnQZCTAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXHMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMz////eMKB4AAAAC3RSTlMAOpE7k5Uvj5kpfRaQSaQAAAABYktHRAsf18TAAAAAHklEQVQI12MQYGBQZmBwTWCo0GSo6AKRQDZQRIABADXXA/UkIpvtAAAAAElFTkSuQmCC) no-repeat center;background-size:4px 9px;width:4px;height:9px}",0),a.insertRule(".iv-promo-website-card-cta-redesign .iv-promo-round-expand-icon:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAADAAAAAwCAQAAAD9CzEMAAAAAmJLR0QA/4ePzL8AAAAJcEhZcwAACxMAAAsTAQCanBgAAAAHdElNRQfgCgUUEztsNfqrAAAAXklEQVRYw+3Uuw2AQAwEUUNXfBpDIvBRMhQwJJAScNrA0r4CdiQHjjAzK4NGKucPAFmCnZcmwcTphBNO9CTGH4VB+/Zm6YlYis9fhedXz38FNvFriCCl808iw8ysrBu65gCeuV/CfgAAAABJRU5ErkJggg==) no-repeat center;background-size:18px 18px;width:18px;height:18px}",
0),a.insertRule(".iv-card-link-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASBAMAAACk4JNkAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAGFBMVEVMaXG7u7u7u7u7u7u7u7u7u7u7u7v///+WKTAlAAAABnRSTlMAFdQWbGj9GiOuAAAAAWJLR0QHFmGI6wAAAEhJREFUCNdjYACBNCBgQGMxMKrBWEJJaRAJRjVlKEsoSQDIAqtSZICwgEIQFkgIZBRECMxiBqsCsVjAqsCygQwwFgMeFgQgswBg2xjLrfC4mgAAAABJRU5ErkJggg==) no-repeat center;background-size:9px;width:9px;height:9px}",0),a.insertRule(".iv-card-playlist-video-count:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYBAMAAAASWSDLAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXH///////////////////////////////////////////9tKdXLAAAAC3RSTlMAvDeyLvxYtDK9Ogx4T1QAAAABYktHRAH/Ai3eAAAAK0lEQVQY02NgoBjshgO8HJoYwKiAMGAD92YHJM7uMCTO9gaEHs4FlPuZAQC8Fj8x/xHjxwAAAABJRU5ErkJggg==) no-repeat center;background-size:24px;width:24px;height:24px}",
0),a.insertRule(".iv-drawer-close-button:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAwAAAAMAgMAAAArG7R0AAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAACVBMVEVMaXH////////OZTV/AAAAAnRSTlMAoKBFbtAAAAABYktHRAH/Ai3eAAAAKUlEQVQI12MIYGBlSGGQBMIUBjbHCQyM0xwYGDIZwBjEBomB5EBqgGoBolQGzYuy51cAAAAASUVORK5CYII=) no-repeat center;background-size:12px;width:12px;height:12px}",0),a.insertRule(".iv-ad-info-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAsAAAALCAMAAACecocUAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAVFBMVEVMaXGUlJSYmJiZmZmYmJiXl5eZmZmZmZmWlpaVlZWOjo6ZmZmSkpKXl5eYmJiYmJiZmZmZmZmZmZmZmZmYmJiJiYmXl5eZmZmYmJiWlpaZmZn///+81lbeAAAAGnRSTlMAE5DM80DliTMMEjccWIM5p1UjaTQNgB5cLlr5mgUAAAABYktHRBsCYNSkAAAAVElEQVQI102NRw7AIBADhw7ppIf/PzQLJ/ZgWSNrFlDaWKMVcs6HmGLwTqjEME6CFDrAXBYIGhNh3TJEg02wHydctvFc7sbrvnXZV8/zfs3T+7u/P7CrAso35YfPAAAAAElFTkSuQmCC) no-repeat center;background-size:11px;width:11px;height:11px}",
0),a.insertRule(".annotation-close-button {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQBAMAAADt3eJSAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAALVBMVEVMaXEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/Pz9aWloBAQGZmZlbW1v///+X9wUzAAAACHRSTlMANprf+g6lyRmB9hUAAAABYktHRA5vvTBPAAAAWUlEQVQI12NgYBAycVZkAIKwDiBIZWBgrQAx2gMY2DrAIIFBomPWju6VHY0MGh1rbu891dHEYNGx9+yd2x3NDB4d3XfO7uhoQTDgUnDFcO1wA+FWwC2FOQMAdKg6tUSAFEAAAAAASUVORK5CYII=) no-repeat center}",0),a.insertRule(".annotation-link-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACIAAAAiCAMAAAANmfvwAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAUVBMVEVMaXH////////////////////////////////////////////////////////////////////////////////////////////////////////JzkR1AAAAGnRSTlMAfXf+c3xsdGdv/GJoXPtXXflSVk5L7DBH9VeFfsQAAAABYktHRAH/Ai3eAAAAgElEQVQ4y93SSQ6AIAwFULSOOOJs739Qf9SF0VA2uNCu+psHaQJK7cVCqY+Rg92PXA++Q84KnCR03UIRJrFEKMEgZYFQhpyzQHSBWJJAdIVUENtJ3SC0mu3EdOh7zXZiBrRdzQLJ0Y1GfOlpVstD3HaZktX9X/gvRCxvxL6FR7IBS1RTM5xIpLoAAAAASUVORK5CYII=) no-repeat center}",
0)},COa=function(a){a=a.createElement({G:"div",
Ha:["annotation","annotation-type-custom"]});g.Zl(a,!1);return a},DOa=function(a,b){b=!b.isCued()&&!g.T(b,1024);
g.VK(a.u,b);g.VK(a.C,b)},EOa=function(a,b,c){a.V=!0;
a.J=g.vt(b,c)},FOa=function(a,b){for(var c={},d=g.r(b.attributes),e=d.next();!e.done;e=d.next())e=e.value,c[e.name]=e.nodeValue;
for(d=0;d<b.childNodes.length;d++)if(e=b.childNodes[d],g.Ka(e)&&1==e.nodeType){if(c[e.tagName])var f=c[e.tagName];else if("data"===e.tagName){0<e.childNodes.length&&(f=e.childNodes[0].nodeValue,c[e.tagName]="string"===typeof f?f.trim():f);continue}else f=[],c[e.tagName]=f;e&&"TEXT"===e.tagName?1===e.childNodes.length&&3===e.childNodes[0].nodeType?f.push(e.childNodes[0].nodeValue):f.push(""):e&&f.push(FOa(a,e))}return c},IOa=function(a){var b=a.player.getVideoData();
if(b.Pa){var c=a.player.W().V.get(b.videoId);if(c){var d={format:"XML",urlParams:{},method:"POST",withCredentials:!0,onFinish:function(e,f,h){e=b.videoId;a.loaded&&a.loadNumber===a.loadNumber&&a.player.getVideoData().videoId===e&&(h=g.mt(h)&&h.responseXML?h.responseXML:null)&&o4(a,h)}};
g.Mu()&&(d.onFinish=GOa(a,d.onFinish));d.postParams={ic_only:"1"};HOa(d,c);a.V=!0;g.vt(b.Pa,d)}}},HOa=function(a,b){a.method="POST";
a.postParams=a.postParams||{};b.uu&&(a.postParams.ic_coll=b.uu);b.Dx&&(a.postParams.ic_xml=b.Dx);b.Rw&&(a.postParams.ic_track=b.Rw)},JOa=function(a){var b=new g.U({G:"div"});
g.Zl(b.element,!1);var c=new b4(a.player,b.element,p4(a));g.J(c,b);b.Ea(a.u.element);c.Bw();return c},p4=function(a){if(!a.S){var b=new A3(a);
g.J(a,b);var c=new g.Zj(a);g.J(a,c);a.S=new wOa(b,c,a.player.W(),a.player.getVideoData(),a.logger,a.player,a.ld)}return a.S},o4=function(a,b){var c=!1,d=b.getElementsByTagName("annotations");
if(d&&!(1>d.length)&&(d=d[0].getAttribute("itct"))){var e=g.Ey();if(e){var f=g.Cy();f&&g.Fz(void 0,e,f,[g.yy(d)])}}b=b.getElementsByTagName("annotation");for(d=0;d<b.length;d++){f=FOa(a,b[d]);e=null;try{if(f){var h=f.id,l=/.+/;var m="string"===typeof h&&null!=l&&null!=h&&h.match(l)?h:"";var n=O3(f.type,KOa),p=O3(f.style,LOa),q=SNa(f.data),t=0!==q.length?JSON.parse(q):{};var u=f.action;f=YNa;if(null==u)var x=null;else if(g.Ja(u)){l=[];for(var y=g.r(u),A=y.next();!A.done;A=y.next()){var E=f(A.value);
E&&l.push(E)}x=l}else{var G=f(u);x=G?[G]:[]}e=m&&n?new R3(m,n,p,x,t):null}else e=null}catch(sa){}if(e)if("branding"===e.type||"promotion"===e.type){f=a;l=e;var F=COa(f),K=null;switch(l.type){case "branding":if(f.player.W().Cb)break;f.u.element.appendChild(F);K=new i4(F,p4(f),l);break;case "promotion":g.RM(f.player,F,4),K=new j4(F,p4(f),l)}K&&K.Bw();if(f=K)g.J(a,f),a.K[e.id]=f}else if("card"===e.type||"drawer"===e.type){a.i||(a.i=JOa(a),g.J(a,a.i));if("card"===e.type){c=a.i;var W=e&&e.data&&e.data.card_type;
f=e.data;if(W)switch(l=f.tracking||{},l={impression:l.impression,click:l.click,close:l.close,UM:l.teaser_impression,qA:l.teaser_click},F=f.tracking_params||{},K=null,W){case "collaborator":e={id:e.id,timestamp:f.timestamp||0,type:f.card_type,teaserText:f.teaser_text,teaserDurationMs:f.teaser_duration_ms,startMs:f.start_ms,autoOpen:f.auto_open||!1,sessionData:f.session_data||{},sponsored:f.sponsored||!1,tracking:l,ul:F.card?g.yy(F.card):null,Ii:F.teaser?g.yy(F.teaser):null,pe:F.icon?g.yy(F.icon):null,
channelId:f.channel_id,customMessage:f.custom_message?f.custom_message:null,profileImageUrl:f.image_url,title:f.title,metaInfo:f.meta_info,url:Q3({pause_on_navigation:f.pause_on_navigation,target:f.target||"new",value:f.url})};e4(c,e);break;case "playlist":e={id:e.id,timestamp:f.timestamp||0,type:f.card_type,teaserText:f.teaser_text,teaserDurationMs:f.teaser_duration_ms,startMs:f.start_ms,autoOpen:f.auto_open||!1,sessionData:f.session_data||{},sponsored:f.sponsored||!1,tracking:l,ul:F.card?g.yy(F.card):
null,Ii:F.teaser?g.yy(F.teaser):null,pe:F.icon?g.yy(F.icon):null,Ow:f.image_url,playlistVideoCount:f.playlist_video_count,customMessage:f.custom_message?f.custom_message:null,title:f.title,metaInfo:f.meta_info,url:Q3({pause_on_navigation:f.pause_on_navigation,target:f.target||"new",value:f.url})};e4(c,e);break;case "productListing":f.signin_url&&(K=Q3({target:"current",value:f.signin_url}));W=[];for(var L=f.offers||[],Z=0;Z<L.length;Z++)W.push(new bOa(g.ud(L[Z].merchant),g.ud(L[Z].price)));e={id:e.id,
timestamp:f.timestamp||0,type:f.card_type,teaserText:f.teaser_text,teaserDurationMs:f.teaser_duration_ms,startMs:f.start_ms,autoOpen:f.auto_open||!1,sessionData:f.session_data||{},sponsored:f.sponsored||!1,tracking:l,ul:F.card?g.yy(F.card):null,Ii:F.teaser?g.yy(F.teaser):null,pe:F.icon?g.yy(F.icon):null,imageUrl:f.image_url,displayDomain:f.display_domain?f.display_domain:null,showLinkIcon:!!f.show_link_icon,xx:f.button_icon_url?f.button_icon_url:null,title:f.title,customMessage:f.custom_message?f.custom_message:
null,url:Q3({pause_on_navigation:f.pause_on_navigation,target:f.target||"new",value:f.url}),T$:K,S$:f.signin_title?f.signin_title:void 0,R$:f.signin_message?f.signin_message:void 0,offers:W};e4(c,e);break;case "simple":e={id:e.id,timestamp:f.timestamp||0,type:f.card_type,teaserText:f.teaser_text,teaserDurationMs:f.teaser_duration_ms,startMs:f.start_ms,autoOpen:f.auto_open||!1,sessionData:f.session_data||{},sponsored:f.sponsored||!1,tracking:l,ul:F.card?g.yy(F.card):null,Ii:F.teaser?g.yy(F.teaser):
null,pe:F.icon?g.yy(F.icon):null,imageUrl:f.image_url,displayDomain:f.display_domain?f.display_domain:null,showLinkIcon:!!f.show_link_icon,xx:f.button_icon_url?f.button_icon_url:null,title:f.title,customMessage:f.custom_message?f.custom_message:null,url:Q3({pause_on_navigation:f.pause_on_navigation,target:f.target||"new",value:f.url})};e4(c,e);break;case "video":e={id:e.id,timestamp:f.timestamp||0,type:f.card_type,teaserText:f.teaser_text,teaserDurationMs:f.teaser_duration_ms,startMs:f.start_ms,autoOpen:f.auto_open||
!1,sessionData:f.session_data||{},sponsored:f.sponsored||!1,tracking:l,ul:F.card?g.yy(F.card):null,Ii:F.teaser?g.yy(F.teaser):null,pe:F.icon?g.yy(F.icon):null,Ow:f.image_url,videoDuration:f.video_duration||null,customMessage:f.custom_message?f.custom_message:null,title:f.title,metaInfo:f.meta_info,isLiveNow:!!f.is_live_now,url:Q3({pause_on_navigation:f.pause_on_navigation,target:f.target||"new",value:f.url})},e4(c,e)}}else fOa(a.i,e);c=!0}}c&&(s3(a.player),a.xz())},MOa=function(a,b){var c=!1;
a.i||(a.i=JOa(a),g.J(a,a.i));for(var d=g.r(b.cards||[]),e=d.next();!e.done;e=d.next())e=e.value,e.cardRenderer&&(gOa(a.i,e.cardRenderer),c=!0);c&&(c=a.i,d=b.headerText?g.zA(b.headerText):"",g.Hg(c.gb,d),c.S&&c.S.setAttribute("title",d),c.context.videoData.eventId&&(c.eventId=c.context.videoData.eventId),c.Ba=b.trackingParams?g.yy(b.trackingParams):null,c.K=b.closeButton.infoCardIconRenderer.trackingParams?g.yy(b.closeButton.infoCardIconRenderer.trackingParams):null,c.pe=b.icon.infoCardIconRenderer.trackingParams?
g.yy(b.icon.infoCardIconRenderer.trackingParams):null,s3(a.player),a.xz())},NOa=function(a,b,c,d,e){if(!a.player.W().Cb){var f=[];
b.navigationEndpoint&&b.navigationEndpoint.browseEndpoint&&b.navigationEndpoint.browseEndpoint.browseId&&f.push(new VNa("openUrl","click",new TNa("/channel/"+b.navigationEndpoint.browseEndpoint.browseId,"new",!0,!0)));var h=b.watermark.thumbnails[0];d={channel_name:b.channelName,end_ms:b.endTimeMs,image_height:h.height,image_type:1,image_url:h.url,image_width:h.width,is_mobile:!1,session_data:{annotation_id:c,ei:e,feature:"iv",itct:b.trackingParams,src_vid:d},start_ms:b.startTimeMs};if(b.subscribeButton&&
b.subscribeButton.subscribeButtonRenderer){d.channel_id=b.subscribeButton.subscribeButtonRenderer.channelId;var l;b=b.subscribeButton.subscribeButtonRenderer;var m,n;h=e=null;b.subscribed?(b.subscriberCountWithUnsubscribeText&&(e=g.zA(b.subscriberCountWithUnsubscribeText)),b.subscriberCountText&&(h=g.zA(b.subscriberCountText))):(b.subscriberCountText&&(e=g.zA(b.subscriberCountText)),b.subscriberCountWithSubscribeText&&(h=g.zA(b.subscriberCountWithSubscribeText)));var p=b.signInEndpoint&&b.signInEndpoint.webNavigationEndpointData&&
b.signInEndpoint.webNavigationEndpointData.url?b.signInEndpoint.webNavigationEndpointData.url:(null===(n=null===(m=null===(l=b.signInEndpoint)||void 0===l?void 0:l.commandMetadata)||void 0===m?void 0:m.webCommandMetadata)||void 0===n?void 0:n.url)||"";l={subscribeText:g.zA(b.unsubscribedButtonText),subscribeCount:e||"",unsubscribeText:g.zA(b.subscribedButtonText),unsubscribeCount:h||"",enabled:b.enabled||!1,classic:!1,subscribed:b.subscribed||!1,feature:"iv",signInUrl:p};d.standalone_subscribe_button_data=
l}f=new R3(c,"branding","branding",f,d);l=COa(a);a.u.element.appendChild(l);f=new i4(l,p4(a),f);f.Bw();g.J(f,f);a.K[c]=f}},GOa=function(a,b){return function(c){for(var d=[],e=0;e<arguments.length;++e)d[e-0]=arguments[e];
a.isDisposed()||a.ea.push(g.Ju(0,function(){b.apply(null,g.v(d))}))}},OOa=function(a){return"annotation-editor"===a||"live-dashboard"===a};
g.KM.prototype.Gs=g.ca(17,function(a,b){var c=g.rN(this.sb());c&&c.Gs(a,b)});
var u3={},v3=null;g.Pa(x3,g.Xq);g.k=x3.prototype;g.k.getDuration=function(){return this.duration};
g.k.play=function(a){if(a||0==this.i)this.progress=0,this.coords=this.u;else if(this.wc())return!1;w3(this);this.startTime=a=g.Oa();-1==this.i&&(this.startTime-=this.duration*this.progress);this.endTime=this.startTime+this.duration;this.D=this.startTime;this.progress||this.sz();this.Zh("play");-1==this.i&&this.Zh("resume");this.i=1;var b=g.Ma(this);b in u3||(u3[b]=this);ENa();FNa(this,a);return!0};
g.k.stop=function(a){w3(this);this.i=0;a&&(this.progress=1);GNa(this,this.progress);this.Zh("stop");this.Wv()};
g.k.pause=function(){this.wc()&&(w3(this),this.i=-1,this.Zh("pause"))};
g.k.ya=function(){0==this.i||this.stop(!1);this.Zh("destroy");x3.Wd.ya.call(this)};
g.k.destroy=function(){this.dispose()};
g.k.rB=function(){this.Zh("animate")};
g.k.Zh=function(a){this.dispatchEvent(new HNa(a,this))};
g.Pa(HNa,g.vf);g.Pa(y3,x3);y3.prototype.C=g.Ga;y3.prototype.rB=function(){this.C();y3.Wd.rB.call(this)};
y3.prototype.Wv=function(){this.C();y3.Wd.Wv.call(this)};
y3.prototype.sz=function(){this.C();y3.Wd.sz.call(this)};
g.Pa(z3,y3);z3.prototype.C=function(){this.element.style.left=Math.round(this.coords[0])+"px";this.element.style.top=Math.round(this.coords[1])+"px"};g.w(A3,g.I);A3.prototype.Ra=function(a,b,c,d){c=(0,g.D)(c,d||this.u);a=g.uu(a,b,c);this.i.push(a);return a};
A3.prototype.Vy=function(a,b,c,d){c=(0,g.D)(c,d||this.u);a=g.Du(a,b,c);this.i.push(a);return a};
A3.prototype.jc=function(a){g.vu(a);g.nb(this.i,a)};
A3.prototype.ya=function(){g.vu(this.i);this.i.length=0;g.I.prototype.ya.call(this)};g.w(E3,g.cN);g.k=E3.prototype;g.k.load=function(){g.cN.prototype.load.call(this);if(!F3(this)){var a=g.Xoa(this.player.getVideoData());a?(a=D3(a,JNa(this)),G3(this,a,!1)):KNa(this)}};
g.k.unload=function(){G3(this,null);this.B&&(this.B.abort(),this.B=null);g.cN.prototype.unload.call(this)};
g.k.We=function(a,b){return F3(this)?"loadCustomEndscreenRenderer"===a?(a=D3(b,"new"),G3(this,a),!0):null:null};
g.k.getOptions=function(){return F3(this)?["loadCustomEndscreenRenderer"]:[]};
g.k.wb=function(){if(this.endscreen&&this.endscreen.elements){var a=this.player.getVideoContentRect();if(a&&0!==a.width&&0!==a.height){var b=this.player.getPlayerSize();if(b&&0!==b.width&&0!==b.height){var c=a.width/a.height;var d=0;for(var e=-1,f=0;f<POa.length;f++){var h=Math.abs(b.width-POa[f]);if(-1===e||d>=h)e=f,d=h}d=QOa[e];this.u&&g.Jl(this.u.element,"outline-width",Math.max(b.width,b.height)+"px");for(b=0;b<this.endscreen.elements.length;++b)if(f=this.endscreen.elements[b].id,e=this.i[f],
h=this.D[f],e&&h){var l=h.width*c/h.aspectRatio;f=Math.round(l*a.height);var m=a.left+Math.round(h.left*a.width),n=a.top+Math.round(h.top*a.height);g.Xl(e.element,Math.round(h.width*a.width),f);g.Ql(e.element,m,n);g.Mq(e.element,ROa);m=h.left+h.width/2;h=h.top+l/2;g.N(e.element,.5>=m&&.5>=h?"ytp-ce-top-left-quad":.5<m&&.5>=h?"ytp-ce-top-right-quad":.5>=m&&.5<h?"ytp-ce-bottom-left-quad":"ytp-ce-bottom-right-quad");g.Mq(e.element,QOa);g.N(e.element,d);(e=g.ng(document,"div","ytp-ce-expanding-overlay-body",
e.element)[0])&&g.Jl(e,"height",f+"px")}}}}};
g.k.onCueRangeEnter=function(a){if(this.endscreen)if("ytp-ce-in-endscreen"===a.getId())N3(this,this.endscreen.impressionUrls),(a=g.Ey())&&this.endscreen.visualElement&&g.Gz(a,this.endscreen.visualElement,void 0);else{a=a.getId().substring(15);var b=this.i[a],c=this.D[a];g.N(b.element,"ytp-ce-element-show");b.element.removeAttribute("aria-hidden");b=this.player.getRootNode();g.N(b,"ytp-ce-shown");N3(this,c.impressionUrls);(b=g.Ey())&&g.Gz(b,c.visualElement,void 0);this.player.W().B&&this.player.Na("endscreenelementshown",
a)}};
g.k.onCueRangeExit=function(a){if("ytp-ce-in-endscreen"!==a.getId()){a=a.getId().substring(15);var b=this.i[a];g.Lq(b.element,"ytp-ce-element-show");b.element.setAttribute("aria-hidden","true");b=this.player.getRootNode();g.Lq(b,"ytp-ce-shown");this.player.W().B&&this.player.Na("endscreenelementhidden",a)}};
g.k.uV=function(a){var b=this;a.target===window&&(new g.M(function(){for(var c=g.r(Object.values(b.i)),d=c.next();!d.done;d=c.next())g.Mq(d.value.element,["ytp-ce-force-expand","ytp-ce-element-hover","ytp-ce-element-shadow-show"])},0)).start()};
var POa=[346,426,470,506,570,640,853,1280,1920],QOa="ytp-ce-size-346 ytp-ce-size-426 ytp-ce-size-470 ytp-ce-size-506 ytp-ce-size-570 ytp-ce-size-640 ytp-ce-size-853 ytp-ce-size-1280 ytp-ce-size-1920".split(" "),ROa=["ytp-ce-top-left-quad","ytp-ce-top-right-quad","ytp-ce-bottom-left-quad","ytp-ce-bottom-right-quad"];var UNa={O_:"current",B5:"new"};var WNa={CLOSE:"close",T5:"openUrl",SUBSCRIBE:"subscribe"},XNa={jY:"click",CLOSE:"close",k1:"hidden",p7:"rollOut",q7:"rollOver",f8:"shown"};R3.prototype.Rd=function(){var a=ZNa(this,function(b){return"openUrl"===b.type&&null!=b.url});
return a?a.url:null};
var LOa={CX:"anchored",GN:"branding",CHANNEL:"channel",M_:"cta",n1:"highlightText",o2:"label",PLAYLIST:"playlist",L6:"popup",o8:"speech",SUBSCRIBE:"subscribe",G8:"title",VIDEO:"video",P9:"website"},KOa={GN:"branding",WX:"card",e0:"drawer",m1:"highlight",U3:"marker",V6:"promotion",TEXT:"text",V9:"widget"};g.w(X3,g.I);g.k=X3.prototype;g.k.addCueRange=function(a,b,c,d,e){a=new g.sA(a,b,{id:c});a.namespace="annotations_module";d&&this.Pa.set(a,d);e&&this.Sa.set(a,e);this.context.I.Id([a])};
g.k.Bw=function(){this.context.u.subscribe("resize",this.zx,this)};
g.k.sB=function(a,b,c,d,e,f){if(this.bb)return!1;f&&(f.stopPropagation(),f.preventDefault());this.navigate(a,c,d,e);return!1};
g.k.show=function(){};
g.k.hide=function(){};
g.k.destroy=function(){g.Eg(this.element)};
g.k.zx=function(){};
g.k.navigate=function(a,b,c,d){var e=this,f=P3(a);if(f){var h=dOa(f,a.target),l=function(){a.i&&e.context.I.pauseVideo();var m=e.context.videoData.D||!1,n=g.Fs(f||"");m&&n&&(n.v||n.list)?e.context.I.Fj(n.v,b,n.list,!1):g.GJ(f||"","current"===h?"_top":void 0,b)};
"new"===h&&(l(),l=null);m4(this.context.logger,c,l,d);cOa(f)||(c=g.Ey(),d=b.itct,c&&d&&g.Oz(c,g.yy(d)))}};
g.k.ya=function(){this.Pa.clear();this.Sa.clear();g.I.prototype.ya.call(this)};
g.k.createElement=function(a){a=new g.U(a);g.J(this,a);return a.element};g.w(b4,X3);g.k=b4.prototype;g.k.isAvailable=function(){var a;if(a=!!this.cards.length)(a=this.I.getRootNode())?(a=g.Yl(a),a=173<a.width&&173<a.height):a=!1;return a};
g.k.zx=function(){var a=this.isAvailable();g.Zl(this.element,a);g.O(this.context.I.getRootNode(),g.WT.IV_DRAWER_ENABLED,a);s3(this.I)};
g.k.destroy=function(){this.I.Gs(!1);try{this.I.getRootNode().removeChild(this.C)}catch(a){}g.cv(this.ea);g.vu(this.xa);this.Ka&&this.Ka.dispose();this.D&&this.D.dispose();X3.prototype.destroy.call(this)};
g.k.nQ=function(){if(this.B){m4(this.context.logger,g4(this).tracking.close);var a=g.Ey();a&&this.K&&g.Oz(a,this.K);a4(this)}};
g.k.zQ=function(){g.O(this.C,"iv-drawer-scrolled",0<this.u.scrollTop)};
g.k.SR=function(){var a=g.Ey(),b=g4(this);b=b?b.pe:this.pe;a&&b&&g.Mz(a,[b])};
g.k.RR=function(){var a=g.Ey(),b=g4(this);b=b?b.pe:this.pe;a&&b&&g.Nz(a,[b])};
g.k.TO=function(){var a=g4(this);m4(this.context.logger,a.tracking.UM);var b=g.Ey();b&&a&&g.Mz(b,[a.Ii,a.pe])};
g.k.TR=function(){var a=g.Ey(),b=g4(this);a&&b&&g.Nz(a,[b.Ii])};
g.k.SO=function(a){var b=g4(this),c=g.Ey();this.i?a?(a=this.context.logger,m4(a,b.tracking.qA),a.I.sendVideoStatsEngageEvent(4,void 0),c&&b.Ii&&g.Oz(c,b.Ii)):(a=this.context.logger,m4(a,b.tracking.qA),a.I.sendVideoStatsEngageEvent(4,void 0),c&&b.pe&&g.Oz(c,b.pe)):(a=this.context.logger,m4(a,b.tracking.qA),a.I.sendVideoStatsEngageEvent(4,void 0),c&&this.pe&&g.Oz(c,this.pe))};g.w(h4,X3);h4.prototype.Bw=function(){X3.prototype.Bw.call(this);rOa(this)};
h4.prototype.show=function(){X3.prototype.show.call(this);var a=g.Ey(),b=this.annotation.data;a&&b&&(b=b.session_data)&&g.Mz(a,[g.yy(b.itct)])};
h4.prototype.hide=function(){X3.prototype.hide.call(this);var a=g.Ey(),b=this.annotation.data;a&&b&&(b=b.session_data)&&g.Nz(a,[g.yy(b.itct)])};g.w(i4,h4);
i4.prototype.show=function(){if(!this.isActive){h4.prototype.show.call(this);if(!this.K){g.N(this.element,"iv-branding");var a=this.annotation.data;this.u=this.createElement({G:"img",Ha:["branding-img","iv-click-target"],X:{"aria-label":"Channel watermark",src:a.image_url,width:a.image_width,height:a.image_height}});g.Zl(this.u,!1);var b=this.createElement({G:"div",Ha:["branding-img-container"]});b.appendChild(this.u);this.element.appendChild(b);(b=this.annotation.Rd())&&Y3(this,this.u,b,this.annotation.id,
a.session_data);vOa(this,a);this.K=!0}g.Zl(this.element,!0);this.isActive=!0;this.u&&sOa(this,this.u)}};
i4.prototype.hide=function(){this.isActive&&(h4.prototype.hide.call(this),g.Zl(this.element,!1),this.isActive=!1)};
i4.prototype.destroy=function(){this.i&&(this.i.dispose(),this.i=null);h4.prototype.destroy.call(this)};g.w(j4,h4);g.k=j4.prototype;g.k.show=function(){this.isActive||(h4.prototype.show.call(this),this.V||(xOa(this),this.V=!0),g.Zl(this.element,!0),g.th(function(){g.Lq(this.element,"iv-promo-inactive")},100,this),this.element.removeAttribute("aria-hidden"),this.isActive=!0,l4(this),yOa(this),zOa(this,this.J))};
g.k.hide=function(){this.isActive&&(g.N(this.element,"iv-promo-inactive"),this.isActive=!1,this.element.setAttribute("aria-hidden","true"))};
g.k.sB=function(a,b,c,d,e,f){return this.isCollapsed?!1:h4.prototype.sB.call(this,a,b,c,d,e,f)};
g.k.eR=function(a){this.S=!0;k4(this,500,a)};
g.k.dR=function(){this.S=!1;AOa(this)};
g.k.YQ=function(a){a.stopPropagation();this.hide()};
g.k.ZQ=function(a){a.stopPropagation();l4(this);this.isCollapsed=!0;g.N(this.element,"iv-promo-collapsed-no-delay");this.D.start()};
g.k.destroy=function(){this.D.dispose();h4.prototype.destroy.call(this)};g.w(n4,g.cN);g.k=n4.prototype;g.k.We=function(a,b){if(!OOa(this.player.W().playerStyle))return null;switch(a){case "loadCustomAnnotationsXml":return(a=g.T1(b))&&o4(this,a),!0;case "removeCustomAnnotationById":return b&&this.i&&(iOa(this.i,b),s3(this.player)),!0}return null};
g.k.getOptions=function(){return OOa(this.player.W().playerStyle)?["loadCustomAnnotationsXml","removeCustomAnnotationById"]:[]};
g.k.kq=function(){var a=this.player.W(),b=this.player.getVideoData();return b.D&&a.pfpChazalUi?!1:1===(a.annotationsLoadPolicy||b.annotationsLoadPolicy)&&!b.sI||a.V.get(b.videoId)||g.kH(b)||g.lH(b)?!0:!1};
g.k.xz=function(){if(this.C){var a=this.player.eb().getVideoContentRect(!0);g.Xl(this.C.element,a.width,a.height);g.Ql(this.C.element,a.left,a.top)}if(this.i){var b=this.player.aj();a=this.i;b=b.width;g.O(a.C,"iv-drawer-small",426>=b);g.O(a.C,"iv-drawer-big",1280<=b)}};
g.k.UO=function(a){DOa(this,a.state);g.T(a.state,2)&&(this.oh()&&this.Zj()&&2!==this.player.getPresentingPlayerType()&&this.setCardsVisible(!1),this.Gs(!1))};
g.k.load=function(){function a(h){var l=b.loadNumber;b.J=null;b.loaded&&b.loadNumber===l&&b.player.getVideoData().videoId===d&&(h=g.mt(h)&&h.responseXML?h.responseXML:null)&&(o4(b,h),g.N(b.player.getRootNode(),"iv-module-loaded"))}
var b=this;g.cN.prototype.load.call(this);DOa(this,this.player.vb());this.loadNumber++;var c=this.player.getVideoData(),d=c.videoId;g.Mu()&&(a=GOa(this,a));var e={format:"XML",onFinish:a,onError:function(){b.J=null},
urlParams:{}};c.isPharma&&(e.urlParams.pharma="1");e.method="POST";e.withCredentials=!0;var f=this.player.W().V.get(d);f&&HOa(e,f);f=f&&(f.Dx||f.uu);if(!c.il||f)c.Pa?EOa(this,c.Pa,e):(this.B=function(){b.onVideoDataChange(e)},this.player.addEventListener("videodatachange",this.B));
g.RM(this.player,this.C.element,4);this.xz();(f=g.kH(c))&&MOa(this,f);(f=g.lH(c))&&f.featuredChannel&&NOa(this,f.featuredChannel,f.annotationId||"branding",c.videoId||null,c.eventId||null)};
g.k.onVideoDataChange=function(a){var b=this.player.getVideoData();b.Pa&&(this.B&&(this.player.removeEventListener("videodatachange",this.B),this.B=null),EOa(this,b.Pa,a))};
g.k.unload=function(){this.player.Te("annotations_module");for(var a=g.r(Object.keys(this.K)),b=a.next();!b.done;b=a.next())this.K[b.value].destroy();this.S=null;this.i&&(this.i.destroy(),this.i=null,s3(this.player));this.V=!1;this.J&&(this.J.abort(),this.J=null);this.K={};this.u.hide();g.cN.prototype.unload.call(this);this.C.detach();this.B&&(this.player.removeEventListener("videodatachange",this.B),this.B=null)};
g.k.PL=function(a){a===this.player.getVideoData().videoId&&(this.loaded?IOa(this):this.load())};
g.k.oh=function(){return!!this.i&&this.i.isAvailable()};
g.k.Zj=function(){this.oh();return!!this.i&&this.i.B};
g.k.setCardsVisible=function(a,b,c){b=void 0===b?!1:b;this.oh();this.i&&(a?c?$3(this.i,c,b):$3(this.i,"YOUTUBE_DRAWER_AUTO_OPEN",b):a4(this.i))};
g.k.Gs=function(a,b){this.player.Z(a?"cardsteasershow":"cardsteaserhide",b)};
g.k.ya=function(){this.player.W().V.unsubscribe("vast_info_card_add",this.PL,this);g.Lq(this.player.getRootNode(),g.WT.IV_DRAWER_OPEN);for(var a=this.ea,b=0,c=a.length;b<c;b++)g.Nu(a[b]);this.ea.length=0;g.cN.prototype.ya.call(this)};
g.k.createElement=function(a){a=new g.U(a);g.J(this,a);return a.element};g.bN("annotations_module",n4);g.bN("creatorendscreen",E3);})(_yt_player);
