# Generated by Django 3.1.4 on 2021-08-13 22:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('instagram', models.URLField(blank=True)),
                ('twitter', models.URLField(blank=True)),
                ('facebook', models.URLField(blank=True)),
                ('bio', models.TextField(blank=True, max_length=500, null=True)),
                ('slug', models.SlugField(blank=True, primary_key=True, serialize=False, unique=True)),
                ('artist_image', models.ImageField(default='default_artist_image.jpg', upload_to='artist_images')),
            ],
        ),
        migrations.CreateModel(
            name='ArtMedium',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, max_length=500, null=True)),
                ('slug', models.SlugField(primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Genres',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('description', models.TextField()),
                ('published', models.DateField(auto_now_add=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('slug', models.SlugField(primary_key=True, serialize=False)),
                ('artist', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='portfolio.artist')),
            ],
        ),
        migrations.CreateModel(
            name='GenericStringTaggedItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.CharField(db_index=True, max_length=50, verbose_name='Object id')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_genericstringtaggeditem_tagged_items', to='contenttypes.contenttype', verbose_name='content type')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_genericstringtaggeditem_items', to='taggit.tag')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ArtItem',
            fields=[
                ('title', models.CharField(max_length=50)),
                ('price', models.PositiveIntegerField(default=99)),
                ('slug', models.SlugField(blank=True, primary_key=True, serialize=False, unique=True)),
                ('cover_image', models.ImageField(default='default_cover_image.jpg', upload_to='cover_images')),
                ('art_story', models.TextField(blank=True, max_length=500, null=True)),
                ('art_mediums', models.ManyToManyField(blank=True, to='portfolio.ArtMedium')),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.artist')),
                ('tags', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='portfolio.GenericStringTaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
        ),
        migrations.AddField(
            model_name='artist',
            name='art_mediums',
            field=models.ManyToManyField(blank=True, to='portfolio.ArtMedium'),
        ),
        migrations.AddField(
            model_name='artist',
            name='genres',
            field=models.ManyToManyField(blank=True, to='portfolio.Genres'),
        ),
        migrations.AddField(
            model_name='artist',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
