# Generated by Django 3.1.4 on 2021-08-31 22:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import portfolio.models
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ArtCommunity',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, max_length=500, null=True)),
                ('slug', models.SlugField(blank=True, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ArtGenre',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, max_length=500, null=True)),
                ('slug', models.SlugField(blank=True, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('instagram', models.URLField(blank=True)),
                ('twitter', models.URLField(blank=True)),
                ('facebook', models.URLField(blank=True)),
                ('bio', models.TextField(blank=True, max_length=500, null=True)),
                ('slug', models.SlugField(blank=True, primary_key=True, serialize=False, unique=True)),
                ('artist_image', models.ImageField(default='default_artist_image.jpg', upload_to='artist_images')),
                ('artist_headshot', models.ImageField(default='default_artist_headshot.jpg', upload_to='artist_headshots')),
                ('studio_image', models.ImageField(default='default_artist_studio.jpg', upload_to='artist_studios')),
                ('art_communities', models.ManyToManyField(blank=True, to='portfolio.ArtCommunity')),
                ('art_genres', models.ManyToManyField(blank=True, to='portfolio.ArtGenre')),
            ],
        ),
        migrations.CreateModel(
            name='ArtMedium',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, max_length=500, null=True)),
                ('slug', models.SlugField(blank=True, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ArtStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('description', models.TextField()),
                ('published', models.DateField(auto_now_add=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('slug', models.SlugField(primary_key=True, serialize=False)),
                ('artist', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='portfolio.artist')),
            ],
        ),
        migrations.CreateModel(
            name='GenericStringTaggedItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.CharField(db_index=True, max_length=50, verbose_name='Object id')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_genericstringtaggeditem_tagged_items', to='contenttypes.contenttype', verbose_name='content type')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_genericstringtaggeditem_items', to='taggit.tag')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ArtItem',
            fields=[
                ('title', models.CharField(max_length=50)),
                ('price', models.PositiveIntegerField(default=99)),
                ('slug', models.SlugField(blank=True, primary_key=True, serialize=False, unique=True)),
                ('cover_image', models.ImageField(default='default_cover_image.jpg', upload_to='cover_images')),
                ('art_story', models.TextField(blank=True, max_length=500, null=True)),
                ('date_submitted', models.DateTimeField(default=django.utils.timezone.now)),
                ('publish_after_approved', models.BooleanField(default=False)),
                ('review_note', models.TextField(blank=True, max_length=1000, null=True)),
                ('urgent_review', models.BooleanField(default=False)),
                ('approval_status', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='portfolio.approvalstatus')),
                ('art_communities', models.ManyToManyField(blank=True, to='portfolio.ArtCommunity')),
                ('art_genres', models.ManyToManyField(blank=True, to='portfolio.ArtGenre')),
                ('art_mediums', models.ManyToManyField(blank=True, to='portfolio.ArtMedium')),
                ('art_status', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='portfolio.artstatus')),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='art_items', to='portfolio.artist')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('tags', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='portfolio.GenericStringTaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
        ),
        migrations.AddField(
            model_name='artist',
            name='art_mediums',
            field=models.ManyToManyField(blank=True, to='portfolio.ArtMedium'),
        ),
        migrations.AddField(
            model_name='artist',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ArtImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to=portfolio.models.rename_image_file)),
                ('art_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='has_images', to='portfolio.artitem')),
            ],
        ),
    ]
