# Generated by Django 3.1.4 on 2021-08-13 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtCommunity',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, max_length=500, null=True)),
                ('slug', models.SlugField(blank=True, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='artmedium',
            name='slug',
            field=models.SlugField(blank=True, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AddField(
            model_name='artitem',
            name='art_communities',
            field=models.ManyToManyField(blank=True, to='portfolio.ArtCommunity'),
        ),
    ]
