# Generated by Django 3.1.4 on 2021-08-10 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_auto_20210805_1911'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='artist_image',
            field=models.ImageField(default='default_artist_image.jpg', upload_to='artist_images'),
        ),
    ]
