# Generated by Django 3.1.4 on 2021-08-13 23:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_auto_20210813_2328'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='genres',
        ),
        migrations.DeleteModel(
            name='Genres',
        ),
    ]
