# Generated by Django 3.1.4 on 2021-08-16 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_auto_20210813_2355'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='art_communities',
            field=models.ManyToManyField(blank=True, to='portfolio.ArtCommunity'),
        ),
        migrations.AddField(
            model_name='artist',
            name='art_genres',
            field=models.ManyToManyField(blank=True, to='portfolio.ArtGenre'),
        ),
    ]
