# Generated by Django 3.1.4 on 2021-08-16 22:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_artstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='artitem',
            name='art_status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='portfolio.artstatus'),
        ),
        migrations.AlterField(
            model_name='artstatus',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
