# Generated by Django 3.1.4 on 2021-09-18 18:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0008_auto_20210915_0924'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='focus_artist',
            field=models.ForeignKey(default='wendywexler', on_delete=django.db.models.deletion.CASCADE, related_name='has_artist', to='portfolio.artist'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='mentioned_artists',
            field=models.ManyToManyField(blank=True, to='portfolio.Artist'),
        ),
    ]
