# Generated by Django 3.1.4 on 2021-08-17 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0008_approvalstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='artitem',
            name='approval_status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='portfolio.approvalstatus'),
        ),
    ]
