# Generated by Django 3.1.4 on 2021-09-20 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0009_auto_20210918_1147'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='showcase',
            field=models.BooleanField(default=False),
        ),
    ]
