# Generated by Django 3.1.4 on 2021-08-17 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0009_artitem_approval_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artitem',
            name='approval_status',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='portfolio.approvalstatus'),
        ),
        migrations.AlterField(
            model_name='artitem',
            name='art_status',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='portfolio.artstatus'),
        ),
    ]
