# Generated by Django 3.1.4 on 2021-09-28 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0010_post_showcase'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='default_hero_image.jpg', upload_to='hero_images')),
                ('unsplash_credit', models.TextField(blank=True, max_length=500, null=True)),
            ],
        ),
    ]
