# Generated by Django 3.1.4 on 2021-08-17 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0011_artitem_date_submitted'),
    ]

    operations = [
        migrations.AddField(
            model_name='artitem',
            name='publish_after_approved',
            field=models.BooleanField(default=False),
        ),
    ]
