# Generated by Django 3.1.4 on 2021-09-28 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0011_heroimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='heroimage',
            name='file_name_text',
            field=models.CharField(default='default', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='heroimage',
            name='image',
            field=models.ImageField(upload_to='hero_images'),
        ),
    ]
