# Generated by Django 3.1.4 on 2021-08-18 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0013_auto_20210818_0011'),
    ]

    operations = [
        migrations.AddField(
            model_name='artitem',
            name='urgent_review',
            field=models.BooleanField(default=False),
        ),
    ]
