# Generated by Django 3.1.4 on 2021-08-19 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0014_artitem_urgent_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='artist_headshot',
            field=models.ImageField(default='default_artist_headshot.jpg', upload_to='artist_headshots'),
        ),
        migrations.AddField(
            model_name='artist',
            name='studio_image',
            field=models.ImageField(default='default_artist_studio.jpg', upload_to='artist_studios'),
        ),
    ]
