# Generated by Django 3.1.4 on 2021-08-20 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0015_auto_20210819_1555'),
    ]

    operations = [
        migrations.AddField(
            model_name='artitem',
            name='art_image_2',
            field=models.ImageField(blank=True, null=True, upload_to='cover_images'),
        ),
        migrations.AddField(
            model_name='artitem',
            name='art_image_3',
            field=models.ImageField(blank=True, null=True, upload_to='cover_images'),
        ),
        migrations.AddField(
            model_name='artitem',
            name='art_image_4',
            field=models.ImageField(blank=True, null=True, upload_to='cover_images'),
        ),
        migrations.AddField(
            model_name='artitem',
            name='art_image_5',
            field=models.ImageField(blank=True, null=True, upload_to='cover_images'),
        ),
    ]
