# Generated by Django 3.1.4 on 2021-08-20 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0016_auto_20210820_1354'),
    ]

    operations = [
        migrations.AddField(
            model_name='artitem',
            name='art_image_6',
            field=models.ImageField(blank=True, null=True, upload_to='cover_images'),
        ),
        migrations.AddField(
            model_name='artitem',
            name='art_image_7',
            field=models.ImageField(blank=True, null=True, upload_to='cover_images'),
        ),
    ]
