# Generated by Django 3.1.4 on 2021-08-20 22:19

from django.db import migrations, models
import django.db.models.deletion
import portfolio.models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0017_auto_20210820_1359'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to=portfolio.models.rename_image_file)),
                ('art_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.artitem')),
            ],
        ),
    ]
