# Generated by Django 3.1.4 on 2021-08-23 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0018_artimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artitem',
            name='art_image_2',
        ),
        migrations.RemoveField(
            model_name='artitem',
            name='art_image_3',
        ),
        migrations.RemoveField(
            model_name='artitem',
            name='art_image_4',
        ),
        migrations.RemoveField(
            model_name='artitem',
            name='art_image_5',
        ),
        migrations.RemoveField(
            model_name='artitem',
            name='art_image_6',
        ),
        migrations.RemoveField(
            model_name='artitem',
            name='art_image_7',
        ),
    ]
